/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AcademicPresentationAuthorResponse } from './AcademicPresentationAuthorResponse';
import {
    AcademicPresentationAuthorResponseFromJSON,
    AcademicPresentationAuthorResponseFromJSONTyped,
    AcademicPresentationAuthorResponseToJSON,
    AcademicPresentationAuthorResponseToJSONTyped,
} from './AcademicPresentationAuthorResponse';

/**
 * 
 * @export
 * @interface AcademicPresentationSummaryResponse
 */
export interface AcademicPresentationSummaryResponse {
    /**
     * 학회 발표 ID
     * @type {number}
     * @memberof AcademicPresentationSummaryResponse
     */
    id?: number;
    /**
     * 발표자 목록 (텍스트)
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    authors?: string;
    /**
     * 연구실 내 발표자 목록
     * @type {Array<AcademicPresentationAuthorResponse>}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationAuthors?: Array<AcademicPresentationAuthorResponse>;
    /**
     * 학회 시작일
     * @type {Date}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationStartDate?: Date;
    /**
     * 학회 종료일
     * @type {Date}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationEndDate?: Date;
    /**
     * 학회 장소
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationLocation?: string;
    /**
     * 학회 주최
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationHost?: string;
    /**
     * 학회명
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationName?: string;
    /**
     * 발표 타입
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    presentationType?: string;
    /**
     * 발표 제목
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    presentationTitle?: string;
    /**
     * 연계 프로젝트 ID
     * @type {number}
     * @memberof AcademicPresentationSummaryResponse
     */
    projectId?: number;
    /**
     * 연계 프로젝트명
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    projectName?: string;
    /**
     * 연계 과제 ID
     * @type {number}
     * @memberof AcademicPresentationSummaryResponse
     */
    taskId?: number;
    /**
     * 연계 과제명
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    taskName?: string;
}

/**
 * Check if a given object implements the AcademicPresentationSummaryResponse interface.
 */
export function instanceOfAcademicPresentationSummaryResponse(value: object): value is AcademicPresentationSummaryResponse {
    return true;
}

export function AcademicPresentationSummaryResponseFromJSON(json: any): AcademicPresentationSummaryResponse {
    return AcademicPresentationSummaryResponseFromJSONTyped(json, false);
}

export function AcademicPresentationSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademicPresentationSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'authors': json['authors'] == null ? undefined : json['authors'],
        'academicPresentationAuthors': json['academicPresentationAuthors'] == null ? undefined : ((json['academicPresentationAuthors'] as Array<any>).map(AcademicPresentationAuthorResponseFromJSON)),
        'academicPresentationStartDate': json['academicPresentationStartDate'] == null ? undefined : (new Date(json['academicPresentationStartDate'])),
        'academicPresentationEndDate': json['academicPresentationEndDate'] == null ? undefined : (new Date(json['academicPresentationEndDate'])),
        'academicPresentationLocation': json['academicPresentationLocation'] == null ? undefined : json['academicPresentationLocation'],
        'academicPresentationHost': json['academicPresentationHost'] == null ? undefined : json['academicPresentationHost'],
        'academicPresentationName': json['academicPresentationName'] == null ? undefined : json['academicPresentationName'],
        'presentationType': json['presentationType'] == null ? undefined : json['presentationType'],
        'presentationTitle': json['presentationTitle'] == null ? undefined : json['presentationTitle'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'taskName': json['taskName'] == null ? undefined : json['taskName'],
    };
}

export function AcademicPresentationSummaryResponseToJSON(json: any): AcademicPresentationSummaryResponse {
    return AcademicPresentationSummaryResponseToJSONTyped(json, false);
}

export function AcademicPresentationSummaryResponseToJSONTyped(value?: AcademicPresentationSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'authors': value['authors'],
        'academicPresentationAuthors': value['academicPresentationAuthors'] == null ? undefined : ((value['academicPresentationAuthors'] as Array<any>).map(AcademicPresentationAuthorResponseToJSON)),
        'academicPresentationStartDate': value['academicPresentationStartDate'] == null ? undefined : ((value['academicPresentationStartDate']).toISOString().substring(0,10)),
        'academicPresentationEndDate': value['academicPresentationEndDate'] == null ? undefined : ((value['academicPresentationEndDate']).toISOString().substring(0,10)),
        'academicPresentationLocation': value['academicPresentationLocation'],
        'academicPresentationHost': value['academicPresentationHost'],
        'academicPresentationName': value['academicPresentationName'],
        'presentationType': value['presentationType'],
        'presentationTitle': value['presentationTitle'],
        'projectId': value['projectId'],
        'projectName': value['projectName'],
        'taskId': value['taskId'],
        'taskName': value['taskName'],
    };
}

