/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcademicPresentationSummaryResponse
 */
export interface AcademicPresentationSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof AcademicPresentationSummaryResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationName?: string;
    /**
     * 
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    presentationTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof AcademicPresentationSummaryResponse
     */
    authors?: string;
    /**
     * 
     * @type {Date}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationStartDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AcademicPresentationSummaryResponse
     */
    academicPresentationEndDate?: Date;
}

/**
 * Check if a given object implements the AcademicPresentationSummaryResponse interface.
 */
export function instanceOfAcademicPresentationSummaryResponse(value: object): value is AcademicPresentationSummaryResponse {
    return true;
}

export function AcademicPresentationSummaryResponseFromJSON(json: any): AcademicPresentationSummaryResponse {
    return AcademicPresentationSummaryResponseFromJSONTyped(json, false);
}

export function AcademicPresentationSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademicPresentationSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'academicPresentationName': json['academicPresentationName'] == null ? undefined : json['academicPresentationName'],
        'presentationTitle': json['presentationTitle'] == null ? undefined : json['presentationTitle'],
        'authors': json['authors'] == null ? undefined : json['authors'],
        'academicPresentationStartDate': json['academicPresentationStartDate'] == null ? undefined : (new Date(json['academicPresentationStartDate'])),
        'academicPresentationEndDate': json['academicPresentationEndDate'] == null ? undefined : (new Date(json['academicPresentationEndDate'])),
    };
}

export function AcademicPresentationSummaryResponseToJSON(json: any): AcademicPresentationSummaryResponse {
    return AcademicPresentationSummaryResponseToJSONTyped(json, false);
}

export function AcademicPresentationSummaryResponseToJSONTyped(value?: AcademicPresentationSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'academicPresentationName': value['academicPresentationName'],
        'presentationTitle': value['presentationTitle'],
        'authors': value['authors'],
        'academicPresentationStartDate': value['academicPresentationStartDate'] == null ? undefined : ((value['academicPresentationStartDate']).toISOString().substring(0,10)),
        'academicPresentationEndDate': value['academicPresentationEndDate'] == null ? undefined : ((value['academicPresentationEndDate']).toISOString().substring(0,10)),
    };
}

