/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcademicPresentationAuthorResponse
 */
export interface AcademicPresentationAuthorResponse {
    /**
     * 사용자 ID
     * @type {number}
     * @memberof AcademicPresentationAuthorResponse
     */
    userId?: number;
    /**
     * 사용자 이름
     * @type {string}
     * @memberof AcademicPresentationAuthorResponse
     */
    userName?: string;
    /**
     * 역할
     * @type {string}
     * @memberof AcademicPresentationAuthorResponse
     */
    role?: string;
}

/**
 * Check if a given object implements the AcademicPresentationAuthorResponse interface.
 */
export function instanceOfAcademicPresentationAuthorResponse(value: object): value is AcademicPresentationAuthorResponse {
    return true;
}

export function AcademicPresentationAuthorResponseFromJSON(json: any): AcademicPresentationAuthorResponse {
    return AcademicPresentationAuthorResponseFromJSONTyped(json, false);
}

export function AcademicPresentationAuthorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademicPresentationAuthorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function AcademicPresentationAuthorResponseToJSON(json: any): AcademicPresentationAuthorResponse {
    return AcademicPresentationAuthorResponseToJSONTyped(json, false);
}

export function AcademicPresentationAuthorResponseToJSONTyped(value?: AcademicPresentationAuthorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'userName': value['userName'],
        'role': value['role'],
    };
}

