/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AcademicPresentationSummaryResponse } from './AcademicPresentationSummaryResponse';
import {
    AcademicPresentationSummaryResponseFromJSON,
    AcademicPresentationSummaryResponseFromJSONTyped,
    AcademicPresentationSummaryResponseToJSON,
    AcademicPresentationSummaryResponseToJSONTyped,
} from './AcademicPresentationSummaryResponse';

/**
 * 
 * @export
 * @interface AcademicPresentationFindAllResponse
 */
export interface AcademicPresentationFindAllResponse {
    /**
     * 학회발표 목록
     * @type {Array<AcademicPresentationSummaryResponse>}
     * @memberof AcademicPresentationFindAllResponse
     */
    presentations?: Array<AcademicPresentationSummaryResponse>;
    /**
     * 전체 페이지 수
     * @type {number}
     * @memberof AcademicPresentationFindAllResponse
     */
    totalPage?: number;
}

/**
 * Check if a given object implements the AcademicPresentationFindAllResponse interface.
 */
export function instanceOfAcademicPresentationFindAllResponse(value: object): value is AcademicPresentationFindAllResponse {
    return true;
}

export function AcademicPresentationFindAllResponseFromJSON(json: any): AcademicPresentationFindAllResponse {
    return AcademicPresentationFindAllResponseFromJSONTyped(json, false);
}

export function AcademicPresentationFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademicPresentationFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'presentations': json['presentations'] == null ? undefined : ((json['presentations'] as Array<any>).map(AcademicPresentationSummaryResponseFromJSON)),
        'totalPage': json['totalPage'] == null ? undefined : json['totalPage'],
    };
}

export function AcademicPresentationFindAllResponseToJSON(json: any): AcademicPresentationFindAllResponse {
    return AcademicPresentationFindAllResponseToJSONTyped(json, false);
}

export function AcademicPresentationFindAllResponseToJSONTyped(value?: AcademicPresentationFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'presentations': value['presentations'] == null ? undefined : ((value['presentations'] as Array<any>).map(AcademicPresentationSummaryResponseToJSON)),
        'totalPage': value['totalPage'],
    };
}

