/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcknowledgementUpdateRequest
 */
export interface AcknowledgementUpdateRequest {
    /**
     * 사사문구
     * @type {string}
     * @memberof AcknowledgementUpdateRequest
     */
    acknowledgementText?: string;
    /**
     * 관련정보
     * @type {string}
     * @memberof AcknowledgementUpdateRequest
     */
    relatedInfo?: string;
    /**
     * 관련링크
     * @type {string}
     * @memberof AcknowledgementUpdateRequest
     */
    relatedLink?: string;
}

/**
 * Check if a given object implements the AcknowledgementUpdateRequest interface.
 */
export function instanceOfAcknowledgementUpdateRequest(value: object): value is AcknowledgementUpdateRequest {
    return true;
}

export function AcknowledgementUpdateRequestFromJSON(json: any): AcknowledgementUpdateRequest {
    return AcknowledgementUpdateRequestFromJSONTyped(json, false);
}

export function AcknowledgementUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcknowledgementUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'acknowledgementText': json['acknowledgementText'] == null ? undefined : json['acknowledgementText'],
        'relatedInfo': json['relatedInfo'] == null ? undefined : json['relatedInfo'],
        'relatedLink': json['relatedLink'] == null ? undefined : json['relatedLink'],
    };
}

export function AcknowledgementUpdateRequestToJSON(json: any): AcknowledgementUpdateRequest {
    return AcknowledgementUpdateRequestToJSONTyped(json, false);
}

export function AcknowledgementUpdateRequestToJSONTyped(value?: AcknowledgementUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acknowledgementText': value['acknowledgementText'],
        'relatedInfo': value['relatedInfo'],
        'relatedLink': value['relatedLink'],
    };
}

