/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSubAffiliationRequest } from './UserSubAffiliationRequest';
import {
  UserSubAffiliationRequestFromJSON,
  UserSubAffiliationRequestFromJSONTyped,
  UserSubAffiliationRequestToJSON,
  UserSubAffiliationRequestToJSONTyped,
} from './UserSubAffiliationRequest';

/**
 *
 * @export
 * @interface AdminUpdateUserRequest
 */
export interface AdminUpdateUserRequest {
  /**
   * 사용자명
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  name: string;
  /**
   * 이메일 주소
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  email: string;
  /**
   * 기관
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  organization: string;
  /**
   * 부서
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  department: string;
  /**
   * 구분 (있으면)
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  position?: AdminUpdateUserRequestPositionEnum;
  /**
   * 서브 소속 (있으면)
   * @type {Array<UserSubAffiliationRequest>}
   * @memberof AdminUpdateUserRequest
   */
  subAffiliations?: Array<UserSubAffiliationRequest>;
  /**
   * 권한
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  role: AdminUpdateUserRequestRoleEnum;
  /**
   * 추가된 연구 분야 ID 목록
   * @type {Array<number>}
   * @memberof AdminUpdateUserRequest
   */
  newCategoryIds?: Array<number>;
  /**
   * 삭제된 연구 분야 ID 목록
   * @type {Array<number>}
   * @memberof AdminUpdateUserRequest
   */
  deletedCategoryIds?: Array<number>;
  /**
   * 전화번호
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  phoneNumber?: string;
  /**
   * 좌석 번호
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  seatNumber?: string;
  /**
   * 연가 개수
   * @type {number}
   * @memberof AdminUpdateUserRequest
   */
  annualLeaveCount?: number;
  /**
   * 비고
   * @type {string}
   * @memberof AdminUpdateUserRequest
   */
  comment?: string;
}

/**
 * @export
 */
export const AdminUpdateUserRequestPositionEnum = {
  Professor: 'PROFESSOR',
  CoPrincipalInvestigator: 'CO_PRINCIPAL_INVESTIGATOR',
  PostdoctoralResearcher: 'POSTDOCTORAL_RESEARCHER',
  PhdStudent: 'PHD_STUDENT',
  MastersStudent: 'MASTERS_STUDENT',
  TranslationalMedicineTrainee: 'TRANSLATIONAL_MEDICINE_TRAINEE',
  ResearcherOrIntern: 'RESEARCHER_OR_INTERN',
  AdministrativeStaff: 'ADMINISTRATIVE_STAFF',
} as const;
export type AdminUpdateUserRequestPositionEnum =
  (typeof AdminUpdateUserRequestPositionEnum)[keyof typeof AdminUpdateUserRequestPositionEnum];

/**
 * @export
 */
export const AdminUpdateUserRequestRoleEnum = {
  User: 'USER',
  Admin: 'ADMIN',
} as const;
export type AdminUpdateUserRequestRoleEnum =
  (typeof AdminUpdateUserRequestRoleEnum)[keyof typeof AdminUpdateUserRequestRoleEnum];

/**
 * Check if a given object implements the AdminUpdateUserRequest interface.
 */
export function instanceOfAdminUpdateUserRequest(
  value: object,
): value is AdminUpdateUserRequest {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('organization' in value) || value['organization'] === undefined)
    return false;
  if (!('department' in value) || value['department'] === undefined)
    return false;
  if (!('role' in value) || value['role'] === undefined) return false;
  return true;
}

export function AdminUpdateUserRequestFromJSON(
  json: any,
): AdminUpdateUserRequest {
  return AdminUpdateUserRequestFromJSONTyped(json, false);
}

export function AdminUpdateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminUpdateUserRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    email: json['email'],
    organization: json['organization'],
    department: json['department'],
    position: json['position'] == null ? undefined : json['position'],
    subAffiliations:
      json['subAffiliations'] == null
        ? undefined
        : (json['subAffiliations'] as Array<any>).map(
            UserSubAffiliationRequestFromJSON,
          ),
    role: json['role'],
    newCategoryIds:
      json['newCategoryIds'] == null ? undefined : json['newCategoryIds'],
    deletedCategoryIds:
      json['deletedCategoryIds'] == null
        ? undefined
        : json['deletedCategoryIds'],
    phoneNumber: json['phoneNumber'] == null ? undefined : json['phoneNumber'],
    seatNumber: json['seatNumber'] == null ? undefined : json['seatNumber'],
    annualLeaveCount:
      json['annualLeaveCount'] == null ? undefined : json['annualLeaveCount'],
    comment: json['comment'] == null ? undefined : json['comment'],
  };
}

export function AdminUpdateUserRequestToJSON(
  json: any,
): AdminUpdateUserRequest {
  return AdminUpdateUserRequestToJSONTyped(json, false);
}

export function AdminUpdateUserRequestToJSONTyped(
  value?: AdminUpdateUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    email: value['email'],
    organization: value['organization'],
    department: value['department'],
    position: value['position'],
    subAffiliations:
      value['subAffiliations'] == null
        ? undefined
        : (value['subAffiliations'] as Array<any>).map(
            UserSubAffiliationRequestToJSON,
          ),
    role: value['role'],
    newCategoryIds: value['newCategoryIds'],
    deletedCategoryIds: value['deletedCategoryIds'],
    phoneNumber: value['phoneNumber'],
    seatNumber: value['seatNumber'],
    annualLeaveCount: value['annualLeaveCount'],
    comment: value['comment'],
  };
}
