/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorSummaryResponse } from './AuthorSummaryResponse';
import {
    AuthorSummaryResponseFromJSON,
    AuthorSummaryResponseFromJSONTyped,
    AuthorSummaryResponseToJSON,
    AuthorSummaryResponseToJSONTyped,
} from './AuthorSummaryResponse';

/**
 * 
 * @export
 * @interface AuthorFindAllResponse
 */
export interface AuthorFindAllResponse {
    /**
     * 저서 목록
     * @type {Array<AuthorSummaryResponse>}
     * @memberof AuthorFindAllResponse
     */
    authors?: Array<AuthorSummaryResponse>;
    /**
     * 전체 페이지 수
     * @type {number}
     * @memberof AuthorFindAllResponse
     */
    totalPage?: number;
}

/**
 * Check if a given object implements the AuthorFindAllResponse interface.
 */
export function instanceOfAuthorFindAllResponse(value: object): value is AuthorFindAllResponse {
    return true;
}

export function AuthorFindAllResponseFromJSON(json: any): AuthorFindAllResponse {
    return AuthorFindAllResponseFromJSONTyped(json, false);
}

export function AuthorFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authors': json['authors'] == null ? undefined : ((json['authors'] as Array<any>).map(AuthorSummaryResponseFromJSON)),
        'totalPage': json['totalPage'] == null ? undefined : json['totalPage'],
    };
}

export function AuthorFindAllResponseToJSON(json: any): AuthorFindAllResponse {
    return AuthorFindAllResponseToJSONTyped(json, false);
}

export function AuthorFindAllResponseToJSONTyped(value?: AuthorFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authors': value['authors'] == null ? undefined : ((value['authors'] as Array<any>).map(AuthorSummaryResponseToJSON)),
        'totalPage': value['totalPage'],
    };
}

