/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AwardRecipientResponse } from './AwardRecipientResponse';
import {
    AwardRecipientResponseFromJSON,
    AwardRecipientResponseFromJSONTyped,
    AwardRecipientResponseToJSON,
    AwardRecipientResponseToJSONTyped,
} from './AwardRecipientResponse';

/**
 * 
 * @export
 * @interface AwardResponse
 */
export interface AwardResponse {
    /**
     * 수상 ID
     * @type {number}
     * @memberof AwardResponse
     */
    id?: number;
    /**
     * 수상자 목록 (텍스트)
     * @type {string}
     * @memberof AwardResponse
     */
    recipients?: string;
    /**
     * 연구실 내 수상자 목록
     * @type {Array<AwardRecipientResponse>}
     * @memberof AwardResponse
     */
    awardRecipients?: Array<AwardRecipientResponse>;
    /**
     * 수상 날짜
     * @type {Date}
     * @memberof AwardResponse
     */
    awardDate?: Date;
    /**
     * 주최 기관
     * @type {string}
     * @memberof AwardResponse
     */
    hostInstitution?: string;
    /**
     * 대회명
     * @type {string}
     * @memberof AwardResponse
     */
    competitionName?: string;
    /**
     * 수상명
     * @type {string}
     * @memberof AwardResponse
     */
    awardName?: string;
    /**
     * 발표 제목
     * @type {string}
     * @memberof AwardResponse
     */
    presentationTitle?: string;
    /**
     * 연계 프로젝트 ID
     * @type {number}
     * @memberof AwardResponse
     */
    projectId?: number;
    /**
     * 연계 프로젝트명
     * @type {string}
     * @memberof AwardResponse
     */
    projectName?: string;
    /**
     * 연계 과제 ID
     * @type {number}
     * @memberof AwardResponse
     */
    taskId?: number;
    /**
     * 연계 과제명
     * @type {string}
     * @memberof AwardResponse
     */
    taskName?: string;
}

/**
 * Check if a given object implements the AwardResponse interface.
 */
export function instanceOfAwardResponse(value: object): value is AwardResponse {
    return true;
}

export function AwardResponseFromJSON(json: any): AwardResponse {
    return AwardResponseFromJSONTyped(json, false);
}

export function AwardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'recipients': json['recipients'] == null ? undefined : json['recipients'],
        'awardRecipients': json['awardRecipients'] == null ? undefined : ((json['awardRecipients'] as Array<any>).map(AwardRecipientResponseFromJSON)),
        'awardDate': json['awardDate'] == null ? undefined : (new Date(json['awardDate'])),
        'hostInstitution': json['hostInstitution'] == null ? undefined : json['hostInstitution'],
        'competitionName': json['competitionName'] == null ? undefined : json['competitionName'],
        'awardName': json['awardName'] == null ? undefined : json['awardName'],
        'presentationTitle': json['presentationTitle'] == null ? undefined : json['presentationTitle'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'taskName': json['taskName'] == null ? undefined : json['taskName'],
    };
}

export function AwardResponseToJSON(json: any): AwardResponse {
    return AwardResponseToJSONTyped(json, false);
}

export function AwardResponseToJSONTyped(value?: AwardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'recipients': value['recipients'],
        'awardRecipients': value['awardRecipients'] == null ? undefined : ((value['awardRecipients'] as Array<any>).map(AwardRecipientResponseToJSON)),
        'awardDate': value['awardDate'] == null ? undefined : ((value['awardDate']).toISOString().substring(0,10)),
        'hostInstitution': value['hostInstitution'],
        'competitionName': value['competitionName'],
        'awardName': value['awardName'],
        'presentationTitle': value['presentationTitle'],
        'projectId': value['projectId'],
        'projectName': value['projectName'],
        'taskId': value['taskId'],
        'taskName': value['taskName'],
    };
}

