/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AwardSummaryResponse
 */
export interface AwardSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof AwardSummaryResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AwardSummaryResponse
     */
    awardName?: string;
    /**
     * 
     * @type {string}
     * @memberof AwardSummaryResponse
     */
    recipients?: string;
    /**
     * 
     * @type {string}
     * @memberof AwardSummaryResponse
     */
    competitionName?: string;
    /**
     * 
     * @type {Date}
     * @memberof AwardSummaryResponse
     */
    awardDate?: Date;
}

/**
 * Check if a given object implements the AwardSummaryResponse interface.
 */
export function instanceOfAwardSummaryResponse(value: object): value is AwardSummaryResponse {
    return true;
}

export function AwardSummaryResponseFromJSON(json: any): AwardSummaryResponse {
    return AwardSummaryResponseFromJSONTyped(json, false);
}

export function AwardSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwardSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'awardName': json['awardName'] == null ? undefined : json['awardName'],
        'recipients': json['recipients'] == null ? undefined : json['recipients'],
        'competitionName': json['competitionName'] == null ? undefined : json['competitionName'],
        'awardDate': json['awardDate'] == null ? undefined : (new Date(json['awardDate'])),
    };
}

export function AwardSummaryResponseToJSON(json: any): AwardSummaryResponse {
    return AwardSummaryResponseToJSONTyped(json, false);
}

export function AwardSummaryResponseToJSONTyped(value?: AwardSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'awardName': value['awardName'],
        'recipients': value['recipients'],
        'competitionName': value['competitionName'],
        'awardDate': value['awardDate'] == null ? undefined : ((value['awardDate']).toISOString().substring(0,10)),
    };
}

