/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardCategorySummary
 */
export interface BoardCategorySummary {
    /**
     * 게시판 분야 ID
     * @type {number}
     * @memberof BoardCategorySummary
     */
    boardCategoryId?: number;
    /**
     * 게시판 분야 이름
     * @type {string}
     * @memberof BoardCategorySummary
     */
    name?: string;
}

/**
 * Check if a given object implements the BoardCategorySummary interface.
 */
export function instanceOfBoardCategorySummary(value: object): value is BoardCategorySummary {
    return true;
}

export function BoardCategorySummaryFromJSON(json: any): BoardCategorySummary {
    return BoardCategorySummaryFromJSONTyped(json, false);
}

export function BoardCategorySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardCategorySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'boardCategoryId': json['boardCategoryId'] == null ? undefined : json['boardCategoryId'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BoardCategorySummaryToJSON(json: any): BoardCategorySummary {
    return BoardCategorySummaryToJSONTyped(json, false);
}

export function BoardCategorySummaryToJSONTyped(value?: BoardCategorySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boardCategoryId': value['boardCategoryId'],
        'name': value['name'],
    };
}

