/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileSummary } from './FileSummary';
import {
    FileSummaryFromJSON,
    FileSummaryFromJSONTyped,
    FileSummaryToJSON,
    FileSummaryToJSONTyped,
} from './FileSummary';
import type { UserSummary } from './UserSummary';
import {
    UserSummaryFromJSON,
    UserSummaryFromJSONTyped,
    UserSummaryToJSON,
    UserSummaryToJSONTyped,
} from './UserSummary';
import type { BoardCategorySummary } from './BoardCategorySummary';
import {
    BoardCategorySummaryFromJSON,
    BoardCategorySummaryFromJSONTyped,
    BoardCategorySummaryToJSON,
    BoardCategorySummaryToJSONTyped,
} from './BoardCategorySummary';

/**
 * 
 * @export
 * @interface BoardDetail
 */
export interface BoardDetail {
    /**
     * 게시판 ID
     * @type {number}
     * @memberof BoardDetail
     */
    boardId?: number;
    /**
     * 작성자 정보
     * @type {UserSummary}
     * @memberof BoardDetail
     */
    author?: UserSummary;
    /**
     * 게시판 분야
     * @type {BoardCategorySummary}
     * @memberof BoardDetail
     */
    boardCategory?: BoardCategorySummary;
    /**
     * 게시판 제목
     * @type {string}
     * @memberof BoardDetail
     */
    title?: string;
    /**
     * 게시판 내용
     * @type {string}
     * @memberof BoardDetail
     */
    content?: string;
    /**
     * 조회수
     * @type {number}
     * @memberof BoardDetail
     */
    viewCount?: number;
    /**
     * 첨부된 파일 정보 목록
     * @type {Array<FileSummary>}
     * @memberof BoardDetail
     */
    files?: Array<FileSummary>;
    /**
     * 게시글 생성 일시
     * @type {Date}
     * @memberof BoardDetail
     */
    createdAt?: Date;
    /**
     * 게시글 수정 일시
     * @type {Date}
     * @memberof BoardDetail
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the BoardDetail interface.
 */
export function instanceOfBoardDetail(value: object): value is BoardDetail {
    return true;
}

export function BoardDetailFromJSON(json: any): BoardDetail {
    return BoardDetailFromJSONTyped(json, false);
}

export function BoardDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'boardId': json['boardId'] == null ? undefined : json['boardId'],
        'author': json['author'] == null ? undefined : UserSummaryFromJSON(json['author']),
        'boardCategory': json['boardCategory'] == null ? undefined : BoardCategorySummaryFromJSON(json['boardCategory']),
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'viewCount': json['viewCount'] == null ? undefined : json['viewCount'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(FileSummaryFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function BoardDetailToJSON(json: any): BoardDetail {
    return BoardDetailToJSONTyped(json, false);
}

export function BoardDetailToJSONTyped(value?: BoardDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boardId': value['boardId'],
        'author': UserSummaryToJSON(value['author']),
        'boardCategory': BoardCategorySummaryToJSON(value['boardCategory']),
        'title': value['title'],
        'content': value['content'],
        'viewCount': value['viewCount'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(FileSummaryToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

