/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardPinRequest
 */
export interface BoardPinRequest {
    /**
     * 게시글 고정 여부
     * @type {boolean}
     * @memberof BoardPinRequest
     */
    isPinned: boolean;
}

/**
 * Check if a given object implements the BoardPinRequest interface.
 */
export function instanceOfBoardPinRequest(value: object): value is BoardPinRequest {
    if (!('isPinned' in value) || value['isPinned'] === undefined) return false;
    return true;
}

export function BoardPinRequestFromJSON(json: any): BoardPinRequest {
    return BoardPinRequestFromJSONTyped(json, false);
}

export function BoardPinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardPinRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isPinned': json['isPinned'],
    };
}

export function BoardPinRequestToJSON(json: any): BoardPinRequest {
    return BoardPinRequestToJSONTyped(json, false);
}

export function BoardPinRequestToJSONTyped(value?: BoardPinRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPinned': value['isPinned'],
    };
}

