/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConferenceRequest
 */
export interface ConferenceRequest {
    /**
     * 발표 제목
     * @type {string}
     * @memberof ConferenceRequest
     */
    presentationTitle: string;
    /**
     * 학회명
     * @type {string}
     * @memberof ConferenceRequest
     */
    conferenceName: string;
    /**
     * 발표자
     * @type {string}
     * @memberof ConferenceRequest
     */
    presenter: string;
    /**
     * 발표일
     * @type {Date}
     * @memberof ConferenceRequest
     */
    presentationDate?: Date;
}

/**
 * Check if a given object implements the ConferenceRequest interface.
 */
export function instanceOfConferenceRequest(value: object): value is ConferenceRequest {
    if (!('presentationTitle' in value) || value['presentationTitle'] === undefined) return false;
    if (!('conferenceName' in value) || value['conferenceName'] === undefined) return false;
    if (!('presenter' in value) || value['presenter'] === undefined) return false;
    return true;
}

export function ConferenceRequestFromJSON(json: any): ConferenceRequest {
    return ConferenceRequestFromJSONTyped(json, false);
}

export function ConferenceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConferenceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'presentationTitle': json['presentationTitle'],
        'conferenceName': json['conferenceName'],
        'presenter': json['presenter'],
        'presentationDate': json['presentationDate'] == null ? undefined : (new Date(json['presentationDate'])),
    };
}

export function ConferenceRequestToJSON(json: any): ConferenceRequest {
    return ConferenceRequestToJSONTyped(json, false);
}

export function ConferenceRequestToJSONTyped(value?: ConferenceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'presentationTitle': value['presentationTitle'],
        'conferenceName': value['conferenceName'],
        'presenter': value['presenter'],
        'presentationDate': value['presentationDate'] == null ? undefined : ((value['presentationDate']).toISOString().substring(0,10)),
    };
}

