/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AwardRecipientRequest } from './AwardRecipientRequest';
import {
    AwardRecipientRequestFromJSON,
    AwardRecipientRequestFromJSONTyped,
    AwardRecipientRequestToJSON,
    AwardRecipientRequestToJSONTyped,
} from './AwardRecipientRequest';

/**
 * 
 * @export
 * @interface CreateAwardRequest
 */
export interface CreateAwardRequest {
    /**
     * 수상자 목록 (텍스트)
     * @type {string}
     * @memberof CreateAwardRequest
     */
    recipients?: string;
    /**
     * 연구실 내 수상자 (구성원 연동)
     * @type {Array<AwardRecipientRequest>}
     * @memberof CreateAwardRequest
     */
    awardRecipients?: Array<AwardRecipientRequest>;
    /**
     * 수상 날짜
     * @type {Date}
     * @memberof CreateAwardRequest
     */
    awardDate?: Date;
    /**
     * 주최 기관
     * @type {string}
     * @memberof CreateAwardRequest
     */
    hostInstitution?: string;
    /**
     * 대회명
     * @type {string}
     * @memberof CreateAwardRequest
     */
    competitionName?: string;
    /**
     * 수상명
     * @type {string}
     * @memberof CreateAwardRequest
     */
    awardName?: string;
    /**
     * 발표 제목
     * @type {string}
     * @memberof CreateAwardRequest
     */
    presentationTitle?: string;
    /**
     * 연계 프로젝트 ID
     * @type {number}
     * @memberof CreateAwardRequest
     */
    projectId?: number;
    /**
     * 연계 과제 ID (선택적)
     * @type {number}
     * @memberof CreateAwardRequest
     */
    taskId?: number;
}

/**
 * Check if a given object implements the CreateAwardRequest interface.
 */
export function instanceOfCreateAwardRequest(value: object): value is CreateAwardRequest {
    return true;
}

export function CreateAwardRequestFromJSON(json: any): CreateAwardRequest {
    return CreateAwardRequestFromJSONTyped(json, false);
}

export function CreateAwardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAwardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipients': json['recipients'] == null ? undefined : json['recipients'],
        'awardRecipients': json['awardRecipients'] == null ? undefined : ((json['awardRecipients'] as Array<any>).map(AwardRecipientRequestFromJSON)),
        'awardDate': json['awardDate'] == null ? undefined : (new Date(json['awardDate'])),
        'hostInstitution': json['hostInstitution'] == null ? undefined : json['hostInstitution'],
        'competitionName': json['competitionName'] == null ? undefined : json['competitionName'],
        'awardName': json['awardName'] == null ? undefined : json['awardName'],
        'presentationTitle': json['presentationTitle'] == null ? undefined : json['presentationTitle'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
    };
}

export function CreateAwardRequestToJSON(json: any): CreateAwardRequest {
    return CreateAwardRequestToJSONTyped(json, false);
}

export function CreateAwardRequestToJSONTyped(value?: CreateAwardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipients': value['recipients'],
        'awardRecipients': value['awardRecipients'] == null ? undefined : ((value['awardRecipients'] as Array<any>).map(AwardRecipientRequestToJSON)),
        'awardDate': value['awardDate'] == null ? undefined : ((value['awardDate']).toISOString().substring(0,10)),
        'hostInstitution': value['hostInstitution'],
        'competitionName': value['competitionName'],
        'awardName': value['awardName'],
        'presentationTitle': value['presentationTitle'],
        'projectId': value['projectId'],
        'taskId': value['taskId'],
    };
}

