/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AcademicPresentationAuthorRequest } from './AcademicPresentationAuthorRequest';
import {
    AcademicPresentationAuthorRequestFromJSON,
    AcademicPresentationAuthorRequestFromJSONTyped,
    AcademicPresentationAuthorRequestToJSON,
    AcademicPresentationAuthorRequestToJSONTyped,
} from './AcademicPresentationAuthorRequest';

/**
 * 
 * @export
 * @interface CreateAcademicPresentationRequest
 */
export interface CreateAcademicPresentationRequest {
    /**
     * 발표자 목록 (텍스트)
     * @type {string}
     * @memberof CreateAcademicPresentationRequest
     */
    authors?: string;
    /**
     * 연구실 내 발표자 (구성원 연동)
     * @type {Array<AcademicPresentationAuthorRequest>}
     * @memberof CreateAcademicPresentationRequest
     */
    academicPresentationAuthors?: Array<AcademicPresentationAuthorRequest>;
    /**
     * 학회 시작일
     * @type {Date}
     * @memberof CreateAcademicPresentationRequest
     */
    academicPresentationStartDate?: Date;
    /**
     * 학회 종료일
     * @type {Date}
     * @memberof CreateAcademicPresentationRequest
     */
    academicPresentationEndDate?: Date;
    /**
     * 학회 장소
     * @type {string}
     * @memberof CreateAcademicPresentationRequest
     */
    academicPresentationLocation?: string;
    /**
     * 학회 주최
     * @type {string}
     * @memberof CreateAcademicPresentationRequest
     */
    academicPresentationHost?: string;
    /**
     * 학회명
     * @type {string}
     * @memberof CreateAcademicPresentationRequest
     */
    academicPresentationName?: string;
    /**
     * 발표 타입
     * @type {string}
     * @memberof CreateAcademicPresentationRequest
     */
    presentationType?: CreateAcademicPresentationRequestPresentationTypeEnum;
    /**
     * 발표 제목
     * @type {string}
     * @memberof CreateAcademicPresentationRequest
     */
    presentationTitle?: string;
    /**
     * 연계 프로젝트 ID
     * @type {number}
     * @memberof CreateAcademicPresentationRequest
     */
    projectId?: number;
    /**
     * 연계 과제 ID
     * @type {number}
     * @memberof CreateAcademicPresentationRequest
     */
    taskId?: number;
}


/**
 * @export
 */
export const CreateAcademicPresentationRequestPresentationTypeEnum = {
    Oral: 'ORAL',
    MiniOral: 'MINI_ORAL',
    Poster: 'POSTER'
} as const;
export type CreateAcademicPresentationRequestPresentationTypeEnum = typeof CreateAcademicPresentationRequestPresentationTypeEnum[keyof typeof CreateAcademicPresentationRequestPresentationTypeEnum];


/**
 * Check if a given object implements the CreateAcademicPresentationRequest interface.
 */
export function instanceOfCreateAcademicPresentationRequest(value: object): value is CreateAcademicPresentationRequest {
    return true;
}

export function CreateAcademicPresentationRequestFromJSON(json: any): CreateAcademicPresentationRequest {
    return CreateAcademicPresentationRequestFromJSONTyped(json, false);
}

export function CreateAcademicPresentationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAcademicPresentationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'authors': json['authors'] == null ? undefined : json['authors'],
        'academicPresentationAuthors': json['academicPresentationAuthors'] == null ? undefined : ((json['academicPresentationAuthors'] as Array<any>).map(AcademicPresentationAuthorRequestFromJSON)),
        'academicPresentationStartDate': json['academicPresentationStartDate'] == null ? undefined : (new Date(json['academicPresentationStartDate'])),
        'academicPresentationEndDate': json['academicPresentationEndDate'] == null ? undefined : (new Date(json['academicPresentationEndDate'])),
        'academicPresentationLocation': json['academicPresentationLocation'] == null ? undefined : json['academicPresentationLocation'],
        'academicPresentationHost': json['academicPresentationHost'] == null ? undefined : json['academicPresentationHost'],
        'academicPresentationName': json['academicPresentationName'] == null ? undefined : json['academicPresentationName'],
        'presentationType': json['presentationType'] == null ? undefined : json['presentationType'],
        'presentationTitle': json['presentationTitle'] == null ? undefined : json['presentationTitle'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
    };
}

export function CreateAcademicPresentationRequestToJSON(json: any): CreateAcademicPresentationRequest {
    return CreateAcademicPresentationRequestToJSONTyped(json, false);
}

export function CreateAcademicPresentationRequestToJSONTyped(value?: CreateAcademicPresentationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authors': value['authors'],
        'academicPresentationAuthors': value['academicPresentationAuthors'] == null ? undefined : ((value['academicPresentationAuthors'] as Array<any>).map(AcademicPresentationAuthorRequestToJSON)),
        'academicPresentationStartDate': value['academicPresentationStartDate'] == null ? undefined : ((value['academicPresentationStartDate']).toISOString().substring(0,10)),
        'academicPresentationEndDate': value['academicPresentationEndDate'] == null ? undefined : ((value['academicPresentationEndDate']).toISOString().substring(0,10)),
        'academicPresentationLocation': value['academicPresentationLocation'],
        'academicPresentationHost': value['academicPresentationHost'],
        'academicPresentationName': value['academicPresentationName'],
        'presentationType': value['presentationType'],
        'presentationTitle': value['presentationTitle'],
        'projectId': value['projectId'],
        'taskId': value['taskId'],
    };
}

