/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatentAuthorRequest } from './PatentAuthorRequest';
import {
    PatentAuthorRequestFromJSON,
    PatentAuthorRequestFromJSONTyped,
    PatentAuthorRequestToJSON,
    PatentAuthorRequestToJSONTyped,
} from './PatentAuthorRequest';

/**
 * 
 * @export
 * @interface CreatePatentRequest
 */
export interface CreatePatentRequest {
    /**
     * 출원일자
     * @type {Date}
     * @memberof CreatePatentRequest
     */
    applicationDate?: Date;
    /**
     * 출원번호
     * @type {string}
     * @memberof CreatePatentRequest
     */
    applicationNumber?: string;
    /**
     * 출원명
     * @type {string}
     * @memberof CreatePatentRequest
     */
    patentName?: string;
    /**
     * 출원인(전체)
     * @type {string}
     * @memberof CreatePatentRequest
     */
    applicantsAll?: string;
    /**
     * 출원인(연구실)
     * @type {Array<PatentAuthorRequest>}
     * @memberof CreatePatentRequest
     */
    patentAuthors?: Array<PatentAuthorRequest>;
    /**
     * 비고
     * @type {string}
     * @memberof CreatePatentRequest
     */
    remarks?: string;
    /**
     * 연계 프로젝트 ID
     * @type {number}
     * @memberof CreatePatentRequest
     */
    projectId?: number;
    /**
     * 연계 과제 ID (선택적)
     * @type {number}
     * @memberof CreatePatentRequest
     */
    taskId?: number;
    /**
     * 첨부 파일 ID 목록
     * @type {Array<string>}
     * @memberof CreatePatentRequest
     */
    fileIds?: Array<string>;
}

/**
 * Check if a given object implements the CreatePatentRequest interface.
 */
export function instanceOfCreatePatentRequest(value: object): value is CreatePatentRequest {
    return true;
}

export function CreatePatentRequestFromJSON(json: any): CreatePatentRequest {
    return CreatePatentRequestFromJSONTyped(json, false);
}

export function CreatePatentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePatentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationDate': json['applicationDate'] == null ? undefined : (new Date(json['applicationDate'])),
        'applicationNumber': json['applicationNumber'] == null ? undefined : json['applicationNumber'],
        'patentName': json['patentName'] == null ? undefined : json['patentName'],
        'applicantsAll': json['applicantsAll'] == null ? undefined : json['applicantsAll'],
        'patentAuthors': json['patentAuthors'] == null ? undefined : ((json['patentAuthors'] as Array<any>).map(PatentAuthorRequestFromJSON)),
        'remarks': json['remarks'] == null ? undefined : json['remarks'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'fileIds': json['fileIds'] == null ? undefined : json['fileIds'],
    };
}

export function CreatePatentRequestToJSON(json: any): CreatePatentRequest {
    return CreatePatentRequestToJSONTyped(json, false);
}

export function CreatePatentRequestToJSONTyped(value?: CreatePatentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applicationDate': value['applicationDate'] == null ? undefined : ((value['applicationDate']).toISOString().substring(0,10)),
        'applicationNumber': value['applicationNumber'],
        'patentName': value['patentName'],
        'applicantsAll': value['applicantsAll'],
        'patentAuthors': value['patentAuthors'] == null ? undefined : ((value['patentAuthors'] as Array<any>).map(PatentAuthorRequestToJSON)),
        'remarks': value['remarks'],
        'projectId': value['projectId'],
        'taskId': value['taskId'],
        'fileIds': value['fileIds'],
    };
}

