/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   * 에러 코드
   * @type {string}
   * @memberof ErrorResponse
   */
  code?: string;
  /**
   * 에러 메시지
   * @type {string}
   * @memberof ErrorResponse
   */
  message?: string;
  /**
   * HTTP 상태 코드
   * @type {number}
   * @memberof ErrorResponse
   */
  status?: number;
  /**
   * 에러 발생 시각 (UTC)
   * @type {Date}
   * @memberof ErrorResponse
   */
  timestamp?: Date;
}

/**
 * Check if a given object implements the ErrorResponse interface.
 */
export function instanceOfErrorResponse(value: object): value is ErrorResponse {
  return true;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
  return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    code: json['code'] == null ? undefined : json['code'],
    message: json['message'] == null ? undefined : json['message'],
    status: json['status'] == null ? undefined : json['status'],
    timestamp:
      json['timestamp'] == null ? undefined : new Date(json['timestamp']),
  };
}

export function ErrorResponseToJSON(json: any): ErrorResponse {
  return ErrorResponseToJSONTyped(json, false);
}

export function ErrorResponseToJSONTyped(
  value?: ErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value['code'],
    message: value['message'],
    status: value['status'],
    timestamp:
      value['timestamp'] == null ? undefined : value['timestamp'].toISOString(),
  };
}
