/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExternalProfessorItem } from './ExternalProfessorItem';
import {
    ExternalProfessorItemFromJSON,
    ExternalProfessorItemFromJSONTyped,
    ExternalProfessorItemToJSON,
    ExternalProfessorItemToJSONTyped,
} from './ExternalProfessorItem';

/**
 * 
 * @export
 * @interface ExternalProfessorFindAllResponse
 */
export interface ExternalProfessorFindAllResponse {
    /**
     * 
     * @type {Array<ExternalProfessorItem>}
     * @memberof ExternalProfessorFindAllResponse
     */
    externalProfessors?: Array<ExternalProfessorItem>;
}

/**
 * Check if a given object implements the ExternalProfessorFindAllResponse interface.
 */
export function instanceOfExternalProfessorFindAllResponse(value: object): value is ExternalProfessorFindAllResponse {
    return true;
}

export function ExternalProfessorFindAllResponseFromJSON(json: any): ExternalProfessorFindAllResponse {
    return ExternalProfessorFindAllResponseFromJSONTyped(json, false);
}

export function ExternalProfessorFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalProfessorFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'externalProfessors': json['externalProfessors'] == null ? undefined : ((json['externalProfessors'] as Array<any>).map(ExternalProfessorItemFromJSON)),
    };
}

export function ExternalProfessorFindAllResponseToJSON(json: any): ExternalProfessorFindAllResponse {
    return ExternalProfessorFindAllResponseToJSONTyped(json, false);
}

export function ExternalProfessorFindAllResponseToJSONTyped(value?: ExternalProfessorFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalProfessors': value['externalProfessors'] == null ? undefined : ((value['externalProfessors'] as Array<any>).map(ExternalProfessorItemToJSON)),
    };
}

