/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalProfessorRequest
 */
export interface ExternalProfessorRequest {
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorRequest
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorRequest
     */
    department?: string;
}

/**
 * Check if a given object implements the ExternalProfessorRequest interface.
 */
export function instanceOfExternalProfessorRequest(value: object): value is ExternalProfessorRequest {
    return true;
}

export function ExternalProfessorRequestFromJSON(json: any): ExternalProfessorRequest {
    return ExternalProfessorRequestFromJSONTyped(json, false);
}

export function ExternalProfessorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalProfessorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'department': json['department'] == null ? undefined : json['department'],
    };
}

export function ExternalProfessorRequestToJSON(json: any): ExternalProfessorRequest {
    return ExternalProfessorRequestToJSONTyped(json, false);
}

export function ExternalProfessorRequestToJSONTyped(value?: ExternalProfessorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'organization': value['organization'],
        'department': value['department'],
    };
}

