/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalProfessorSummary
 */
export interface ExternalProfessorSummary {
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorSummary
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorSummary
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorSummary
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorSummary
     */
    position?: string;
}

/**
 * Check if a given object implements the ExternalProfessorSummary interface.
 */
export function instanceOfExternalProfessorSummary(value: object): value is ExternalProfessorSummary {
    return true;
}

export function ExternalProfessorSummaryFromJSON(json: any): ExternalProfessorSummary {
    return ExternalProfessorSummaryFromJSONTyped(json, false);
}

export function ExternalProfessorSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalProfessorSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'department': json['department'] == null ? undefined : json['department'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function ExternalProfessorSummaryToJSON(json: any): ExternalProfessorSummary {
    return ExternalProfessorSummaryToJSONTyped(json, false);
}

export function ExternalProfessorSummaryToJSONTyped(value?: ExternalProfessorSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'organization': value['organization'],
        'department': value['department'],
        'position': value['position'],
    };
}

