/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalProfessorItem
 */
export interface ExternalProfessorItem {
    /**
     * 
     * @type {number}
     * @memberof ExternalProfessorItem
     */
    professorId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorItem
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalProfessorItem
     */
    department?: string;
}

/**
 * Check if a given object implements the ExternalProfessorItem interface.
 */
export function instanceOfExternalProfessorItem(value: object): value is ExternalProfessorItem {
    return true;
}

export function ExternalProfessorItemFromJSON(json: any): ExternalProfessorItem {
    return ExternalProfessorItemFromJSONTyped(json, false);
}

export function ExternalProfessorItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalProfessorItem {
    if (json == null) {
        return json;
    }
    return {
        
        'professorId': json['professorId'] == null ? undefined : json['professorId'],
        'name': json['name'] == null ? undefined : json['name'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'department': json['department'] == null ? undefined : json['department'],
    };
}

export function ExternalProfessorItemToJSON(json: any): ExternalProfessorItem {
    return ExternalProfessorItemToJSONTyped(json, false);
}

export function ExternalProfessorItemToJSONTyped(value?: ExternalProfessorItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'professorId': value['professorId'],
        'name': value['name'],
        'organization': value['organization'],
        'department': value['department'],
    };
}

