/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FilePresignedUrlResponse
 */
export interface FilePresignedUrlResponse {
  /**
   *
   * @type {string}
   * @memberof FilePresignedUrlResponse
   */
  uuid?: string;
  /**
   *
   * @type {string}
   * @memberof FilePresignedUrlResponse
   */
  presignedUrl?: string;
}

/**
 * Check if a given object implements the FilePresignedUrlResponse interface.
 */
export function instanceOfFilePresignedUrlResponse(
  value: object,
): value is FilePresignedUrlResponse {
  return true;
}

export function FilePresignedUrlResponseFromJSON(
  json: any,
): FilePresignedUrlResponse {
  return FilePresignedUrlResponseFromJSONTyped(json, false);
}

export function FilePresignedUrlResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FilePresignedUrlResponse {
  if (json == null) {
    return json;
  }
  return {
    uuid: json['uuid'] == null ? undefined : json['uuid'],
    presignedUrl:
      json['presignedUrl'] == null ? undefined : json['presignedUrl'],
  };
}

export function FilePresignedUrlResponseToJSON(
  json: any,
): FilePresignedUrlResponse {
  return FilePresignedUrlResponseToJSONTyped(json, false);
}

export function FilePresignedUrlResponseToJSONTyped(
  value?: FilePresignedUrlResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    uuid: value['uuid'],
    presignedUrl: value['presignedUrl'],
  };
}
