/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeaveDetail } from './LeaveDetail';
import {
    LeaveDetailFromJSON,
    LeaveDetailFromJSONTyped,
    LeaveDetailToJSON,
    LeaveDetailToJSONTyped,
} from './LeaveDetail';

/**
 * 
 * @export
 * @interface LeaveFindAllResponse
 */
export interface LeaveFindAllResponse {
    /**
     * 
     * @type {Array<LeaveDetail>}
     * @memberof LeaveFindAllResponse
     */
    leaves?: Array<LeaveDetail>;
}

/**
 * Check if a given object implements the LeaveFindAllResponse interface.
 */
export function instanceOfLeaveFindAllResponse(value: object): value is LeaveFindAllResponse {
    return true;
}

export function LeaveFindAllResponseFromJSON(json: any): LeaveFindAllResponse {
    return LeaveFindAllResponseFromJSONTyped(json, false);
}

export function LeaveFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaveFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'leaves': json['leaves'] == null ? undefined : ((json['leaves'] as Array<any>).map(LeaveDetailFromJSON)),
    };
}

export function LeaveFindAllResponseToJSON(json: any): LeaveFindAllResponse {
    return LeaveFindAllResponseToJSONTyped(json, false);
}

export function LeaveFindAllResponseToJSONTyped(value?: LeaveFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'leaves': value['leaves'] == null ? undefined : ((value['leaves'] as Array<any>).map(LeaveDetailToJSON)),
    };
}

