/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
  /**
   * 사용자 이메일 주소
   * @type {string}
   * @memberof LoginRequest
   */
  email: string;
  /**
   * 사용자 비밀번호
   * @type {string}
   * @memberof LoginRequest
   */
  password: string;
}

/**
 * Check if a given object implements the LoginRequest interface.
 */
export function instanceOfLoginRequest(value: object): value is LoginRequest {
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  return true;
}

export function LoginRequestFromJSON(json: any): LoginRequest {
  return LoginRequestFromJSONTyped(json, false);
}

export function LoginRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginRequest {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function LoginRequestToJSON(json: any): LoginRequest {
  return LoginRequestToJSONTyped(json, false);
}

export function LoginRequestToJSONTyped(
  value?: LoginRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    password: value['password'],
  };
}
