/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sortnull } from './Sortnull';
import {
    SortnullFromJSON,
    SortnullFromJSONTyped,
    SortnullToJSON,
    SortnullToJSONTyped,
} from './Sortnull';
import type { Pageablenull } from './Pageablenull';
import {
    PageablenullFromJSON,
    PageablenullFromJSONTyped,
    PageablenullToJSON,
    PageablenullToJSONTyped,
} from './Pageablenull';
import type { AcademicPresentationSummaryResponse } from './AcademicPresentationSummaryResponse';
import {
    AcademicPresentationSummaryResponseFromJSON,
    AcademicPresentationSummaryResponseFromJSONTyped,
    AcademicPresentationSummaryResponseToJSON,
    AcademicPresentationSummaryResponseToJSONTyped,
} from './AcademicPresentationSummaryResponse';

/**
 * 
 * @export
 * @interface PageAcademicPresentationSummaryResponse
 */
export interface PageAcademicPresentationSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    size?: number;
    /**
     * 
     * @type {Array<AcademicPresentationSummaryResponse>}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    content?: Array<AcademicPresentationSummaryResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    number?: number;
    /**
     * 
     * @type {Sortnull}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    sort?: Sortnull;
    /**
     * 
     * @type {number}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    numberOfElements?: number;
    /**
     * 
     * @type {Pageablenull}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    pageable?: Pageablenull;
    /**
     * 
     * @type {boolean}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageAcademicPresentationSummaryResponse
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageAcademicPresentationSummaryResponse interface.
 */
export function instanceOfPageAcademicPresentationSummaryResponse(value: object): value is PageAcademicPresentationSummaryResponse {
    return true;
}

export function PageAcademicPresentationSummaryResponseFromJSON(json: any): PageAcademicPresentationSummaryResponse {
    return PageAcademicPresentationSummaryResponseFromJSONTyped(json, false);
}

export function PageAcademicPresentationSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageAcademicPresentationSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(AcademicPresentationSummaryResponseFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortnullFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageablenullFromJSON(json['pageable']),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageAcademicPresentationSummaryResponseToJSON(json: any): PageAcademicPresentationSummaryResponse {
    return PageAcademicPresentationSummaryResponseToJSONTyped(json, false);
}

export function PageAcademicPresentationSummaryResponseToJSONTyped(value?: PageAcademicPresentationSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(AcademicPresentationSummaryResponseToJSON)),
        'number': value['number'],
        'sort': SortnullToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageablenullToJSON(value['pageable']),
        'first': value['first'],
        'last': value['last'],
        'empty': value['empty'],
    };
}

