/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaperCorrespondingAuthorResponse
 */
export interface PaperCorrespondingAuthorResponse {
    /**
     * 외부 교수 ID
     * @type {number}
     * @memberof PaperCorrespondingAuthorResponse
     */
    externalProfessorId?: number;
    /**
     * 외부 교수명
     * @type {string}
     * @memberof PaperCorrespondingAuthorResponse
     */
    externalProfessorName?: string;
    /**
     * 역할
     * @type {string}
     * @memberof PaperCorrespondingAuthorResponse
     */
    role?: string;
}

/**
 * Check if a given object implements the PaperCorrespondingAuthorResponse interface.
 */
export function instanceOfPaperCorrespondingAuthorResponse(value: object): value is PaperCorrespondingAuthorResponse {
    return true;
}

export function PaperCorrespondingAuthorResponseFromJSON(json: any): PaperCorrespondingAuthorResponse {
    return PaperCorrespondingAuthorResponseFromJSONTyped(json, false);
}

export function PaperCorrespondingAuthorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperCorrespondingAuthorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'externalProfessorId': json['externalProfessorId'] == null ? undefined : json['externalProfessorId'],
        'externalProfessorName': json['externalProfessorName'] == null ? undefined : json['externalProfessorName'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function PaperCorrespondingAuthorResponseToJSON(json: any): PaperCorrespondingAuthorResponse {
    return PaperCorrespondingAuthorResponseToJSONTyped(json, false);
}

export function PaperCorrespondingAuthorResponseToJSONTyped(value?: PaperCorrespondingAuthorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalProfessorId': value['externalProfessorId'],
        'externalProfessorName': value['externalProfessorName'],
        'role': value['role'],
    };
}

