/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 논문 저자 요청 DTO
 * @export
 * @interface PaperAuthorRequest
 */
export interface PaperAuthorRequest {
    /**
     * 사용자 ID
     * @type {number}
     * @memberof PaperAuthorRequest
     */
    userId?: number;
    /**
     * 저자 역할
     * @type {string}
     * @memberof PaperAuthorRequest
     */
    role?: string;
}

/**
 * Check if a given object implements the PaperAuthorRequest interface.
 */
export function instanceOfPaperAuthorRequest(value: object): value is PaperAuthorRequest {
    return true;
}

export function PaperAuthorRequestFromJSON(json: any): PaperAuthorRequest {
    return PaperAuthorRequestFromJSONTyped(json, false);
}

export function PaperAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperAuthorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function PaperAuthorRequestToJSON(json: any): PaperAuthorRequest {
    return PaperAuthorRequestToJSONTyped(json, false);
}

export function PaperAuthorRequestToJSONTyped(value?: PaperAuthorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'role': value['role'],
    };
}

