/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaperAuthorResponse
 */
export interface PaperAuthorResponse {
    /**
     * 
     * @type {number}
     * @memberof PaperAuthorResponse
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof PaperAuthorResponse
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperAuthorResponse
     */
    role?: string;
}

/**
 * Check if a given object implements the PaperAuthorResponse interface.
 */
export function instanceOfPaperAuthorResponse(value: object): value is PaperAuthorResponse {
    return true;
}

export function PaperAuthorResponseFromJSON(json: any): PaperAuthorResponse {
    return PaperAuthorResponseFromJSONTyped(json, false);
}

export function PaperAuthorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperAuthorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function PaperAuthorResponseToJSON(json: any): PaperAuthorResponse {
    return PaperAuthorResponseToJSONTyped(json, false);
}

export function PaperAuthorResponseToJSONTyped(value?: PaperAuthorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'userName': value['userName'],
        'role': value['role'],
    };
}

