/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaperSummaryResponse
 */
export interface PaperSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof PaperSummaryResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PaperSummaryResponse
     */
    paperTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperSummaryResponse
     */
    journalName?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperSummaryResponse
     */
    allAuthors?: string;
    /**
     * 
     * @type {Date}
     * @memberof PaperSummaryResponse
     */
    acceptDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PaperSummaryResponse
     */
    publishDate?: Date;
}

/**
 * Check if a given object implements the PaperSummaryResponse interface.
 */
export function instanceOfPaperSummaryResponse(value: object): value is PaperSummaryResponse {
    return true;
}

export function PaperSummaryResponseFromJSON(json: any): PaperSummaryResponse {
    return PaperSummaryResponseFromJSONTyped(json, false);
}

export function PaperSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'paperTitle': json['paperTitle'] == null ? undefined : json['paperTitle'],
        'journalName': json['journalName'] == null ? undefined : json['journalName'],
        'allAuthors': json['allAuthors'] == null ? undefined : json['allAuthors'],
        'acceptDate': json['acceptDate'] == null ? undefined : (new Date(json['acceptDate'])),
        'publishDate': json['publishDate'] == null ? undefined : (new Date(json['publishDate'])),
    };
}

export function PaperSummaryResponseToJSON(json: any): PaperSummaryResponse {
    return PaperSummaryResponseToJSONTyped(json, false);
}

export function PaperSummaryResponseToJSONTyped(value?: PaperSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'paperTitle': value['paperTitle'],
        'journalName': value['journalName'],
        'allAuthors': value['allAuthors'],
        'acceptDate': value['acceptDate'] == null ? undefined : ((value['acceptDate']).toISOString().substring(0,10)),
        'publishDate': value['publishDate'] == null ? undefined : ((value['publishDate']).toISOString().substring(0,10)),
    };
}

