/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaperSummaryResponse } from './PaperSummaryResponse';
import {
    PaperSummaryResponseFromJSON,
    PaperSummaryResponseFromJSONTyped,
    PaperSummaryResponseToJSON,
    PaperSummaryResponseToJSONTyped,
} from './PaperSummaryResponse';

/**
 * 
 * @export
 * @interface PaperFindAllResponse
 */
export interface PaperFindAllResponse {
    /**
     * 논문 목록
     * @type {Array<PaperSummaryResponse>}
     * @memberof PaperFindAllResponse
     */
    papers?: Array<PaperSummaryResponse>;
    /**
     * 전체 페이지 수
     * @type {number}
     * @memberof PaperFindAllResponse
     */
    totalPage?: number;
}

/**
 * Check if a given object implements the PaperFindAllResponse interface.
 */
export function instanceOfPaperFindAllResponse(value: object): value is PaperFindAllResponse {
    return true;
}

export function PaperFindAllResponseFromJSON(json: any): PaperFindAllResponse {
    return PaperFindAllResponseFromJSONTyped(json, false);
}

export function PaperFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'papers': json['papers'] == null ? undefined : ((json['papers'] as Array<any>).map(PaperSummaryResponseFromJSON)),
        'totalPage': json['totalPage'] == null ? undefined : json['totalPage'],
    };
}

export function PaperFindAllResponseToJSON(json: any): PaperFindAllResponse {
    return PaperFindAllResponseToJSONTyped(json, false);
}

export function PaperFindAllResponseToJSONTyped(value?: PaperFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'papers': value['papers'] == null ? undefined : ((value['papers'] as Array<any>).map(PaperSummaryResponseToJSON)),
        'totalPage': value['totalPage'],
    };
}

