/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JournalResponse } from './JournalResponse';
import {
    JournalResponseFromJSON,
    JournalResponseFromJSONTyped,
    JournalResponseToJSON,
    JournalResponseToJSONTyped,
} from './JournalResponse';
import type { FileSummary } from './FileSummary';
import {
    FileSummaryFromJSON,
    FileSummaryFromJSONTyped,
    FileSummaryToJSON,
    FileSummaryToJSONTyped,
} from './FileSummary';
import type { PaperAuthorResponse } from './PaperAuthorResponse';
import {
    PaperAuthorResponseFromJSON,
    PaperAuthorResponseFromJSONTyped,
    PaperAuthorResponseToJSON,
    PaperAuthorResponseToJSONTyped,
} from './PaperAuthorResponse';

/**
 * 
 * @export
 * @interface PaperResponse
 */
export interface PaperResponse {
    /**
     * 
     * @type {number}
     * @memberof PaperResponse
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PaperResponse
     */
    acceptDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PaperResponse
     */
    publishDate?: Date;
    /**
     * 
     * @type {JournalResponse}
     * @memberof PaperResponse
     */
    journal?: JournalResponse;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    paperTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    allAuthors?: string;
    /**
     * 
     * @type {number}
     * @memberof PaperResponse
     */
    authorCount?: number;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    firstAuthor?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    coAuthors?: string;
    /**
     * 
     * @type {Array<PaperAuthorResponse>}
     * @memberof PaperResponse
     */
    paperAuthors?: Array<PaperAuthorResponse>;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    vol?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    page?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    paperLink?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    doi?: string;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    pmid?: string;
    /**
     * 
     * @type {number}
     * @memberof PaperResponse
     */
    citations?: number;
    /**
     * 
     * @type {string}
     * @memberof PaperResponse
     */
    professorRole?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaperResponse
     */
    isRepresentative?: boolean;
    /**
     * 
     * @type {Array<FileSummary>}
     * @memberof PaperResponse
     */
    files?: Array<FileSummary>;
}

/**
 * Check if a given object implements the PaperResponse interface.
 */
export function instanceOfPaperResponse(value: object): value is PaperResponse {
    return true;
}

export function PaperResponseFromJSON(json: any): PaperResponse {
    return PaperResponseFromJSONTyped(json, false);
}

export function PaperResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'acceptDate': json['acceptDate'] == null ? undefined : (new Date(json['acceptDate'])),
        'publishDate': json['publishDate'] == null ? undefined : (new Date(json['publishDate'])),
        'journal': json['journal'] == null ? undefined : JournalResponseFromJSON(json['journal']),
        'paperTitle': json['paperTitle'] == null ? undefined : json['paperTitle'],
        'allAuthors': json['allAuthors'] == null ? undefined : json['allAuthors'],
        'authorCount': json['authorCount'] == null ? undefined : json['authorCount'],
        'firstAuthor': json['firstAuthor'] == null ? undefined : json['firstAuthor'],
        'coAuthors': json['coAuthors'] == null ? undefined : json['coAuthors'],
        'paperAuthors': json['paperAuthors'] == null ? undefined : ((json['paperAuthors'] as Array<any>).map(PaperAuthorResponseFromJSON)),
        'vol': json['vol'] == null ? undefined : json['vol'],
        'page': json['page'] == null ? undefined : json['page'],
        'paperLink': json['paperLink'] == null ? undefined : json['paperLink'],
        'doi': json['doi'] == null ? undefined : json['doi'],
        'pmid': json['pmid'] == null ? undefined : json['pmid'],
        'citations': json['citations'] == null ? undefined : json['citations'],
        'professorRole': json['professorRole'] == null ? undefined : json['professorRole'],
        'isRepresentative': json['isRepresentative'] == null ? undefined : json['isRepresentative'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(FileSummaryFromJSON)),
    };
}

export function PaperResponseToJSON(json: any): PaperResponse {
    return PaperResponseToJSONTyped(json, false);
}

export function PaperResponseToJSONTyped(value?: PaperResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'acceptDate': value['acceptDate'] == null ? undefined : ((value['acceptDate']).toISOString().substring(0,10)),
        'publishDate': value['publishDate'] == null ? undefined : ((value['publishDate']).toISOString().substring(0,10)),
        'journal': JournalResponseToJSON(value['journal']),
        'paperTitle': value['paperTitle'],
        'allAuthors': value['allAuthors'],
        'authorCount': value['authorCount'],
        'firstAuthor': value['firstAuthor'],
        'coAuthors': value['coAuthors'],
        'paperAuthors': value['paperAuthors'] == null ? undefined : ((value['paperAuthors'] as Array<any>).map(PaperAuthorResponseToJSON)),
        'vol': value['vol'],
        'page': value['page'],
        'paperLink': value['paperLink'],
        'doi': value['doi'],
        'pmid': value['pmid'],
        'citations': value['citations'],
        'professorRole': value['professorRole'],
        'isRepresentative': value['isRepresentative'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(FileSummaryToJSON)),
    };
}

