/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatentAuthorResponse } from './PatentAuthorResponse';
import {
    PatentAuthorResponseFromJSON,
    PatentAuthorResponseFromJSONTyped,
    PatentAuthorResponseToJSON,
    PatentAuthorResponseToJSONTyped,
} from './PatentAuthorResponse';
import type { FileSummary } from './FileSummary';
import {
    FileSummaryFromJSON,
    FileSummaryFromJSONTyped,
    FileSummaryToJSON,
    FileSummaryToJSONTyped,
} from './FileSummary';

/**
 * 
 * @export
 * @interface PatentSummaryResponse
 */
export interface PatentSummaryResponse {
    /**
     * 특허 ID
     * @type {number}
     * @memberof PatentSummaryResponse
     */
    id?: number;
    /**
     * 출원일자
     * @type {Date}
     * @memberof PatentSummaryResponse
     */
    applicationDate?: Date;
    /**
     * 출원번호
     * @type {string}
     * @memberof PatentSummaryResponse
     */
    applicationNumber?: string;
    /**
     * 출원명
     * @type {string}
     * @memberof PatentSummaryResponse
     */
    patentName?: string;
    /**
     * 출원인(전체)
     * @type {string}
     * @memberof PatentSummaryResponse
     */
    applicantsAll?: string;
    /**
     * 출원인(연구실)
     * @type {Array<PatentAuthorResponse>}
     * @memberof PatentSummaryResponse
     */
    patentAuthors?: Array<PatentAuthorResponse>;
    /**
     * 비고
     * @type {string}
     * @memberof PatentSummaryResponse
     */
    remarks?: string;
    /**
     * 연계 프로젝트 ID
     * @type {number}
     * @memberof PatentSummaryResponse
     */
    projectId?: number;
    /**
     * 연계 프로젝트명
     * @type {string}
     * @memberof PatentSummaryResponse
     */
    projectName?: string;
    /**
     * 연계 과제 ID
     * @type {number}
     * @memberof PatentSummaryResponse
     */
    taskId?: number;
    /**
     * 연계 과제명
     * @type {string}
     * @memberof PatentSummaryResponse
     */
    taskName?: string;
    /**
     * 첨부 파일 목록
     * @type {Array<FileSummary>}
     * @memberof PatentSummaryResponse
     */
    files?: Array<FileSummary>;
}

/**
 * Check if a given object implements the PatentSummaryResponse interface.
 */
export function instanceOfPatentSummaryResponse(value: object): value is PatentSummaryResponse {
    return true;
}

export function PatentSummaryResponseFromJSON(json: any): PatentSummaryResponse {
    return PatentSummaryResponseFromJSONTyped(json, false);
}

export function PatentSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatentSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'applicationDate': json['applicationDate'] == null ? undefined : (new Date(json['applicationDate'])),
        'applicationNumber': json['applicationNumber'] == null ? undefined : json['applicationNumber'],
        'patentName': json['patentName'] == null ? undefined : json['patentName'],
        'applicantsAll': json['applicantsAll'] == null ? undefined : json['applicantsAll'],
        'patentAuthors': json['patentAuthors'] == null ? undefined : ((json['patentAuthors'] as Array<any>).map(PatentAuthorResponseFromJSON)),
        'remarks': json['remarks'] == null ? undefined : json['remarks'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'taskName': json['taskName'] == null ? undefined : json['taskName'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(FileSummaryFromJSON)),
    };
}

export function PatentSummaryResponseToJSON(json: any): PatentSummaryResponse {
    return PatentSummaryResponseToJSONTyped(json, false);
}

export function PatentSummaryResponseToJSONTyped(value?: PatentSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'applicationDate': value['applicationDate'] == null ? undefined : ((value['applicationDate']).toISOString().substring(0,10)),
        'applicationNumber': value['applicationNumber'],
        'patentName': value['patentName'],
        'applicantsAll': value['applicantsAll'],
        'patentAuthors': value['patentAuthors'] == null ? undefined : ((value['patentAuthors'] as Array<any>).map(PatentAuthorResponseToJSON)),
        'remarks': value['remarks'],
        'projectId': value['projectId'],
        'projectName': value['projectName'],
        'taskId': value['taskId'],
        'taskName': value['taskName'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(FileSummaryToJSON)),
    };
}

