/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatentResponse
 */
export interface PatentResponse {
    /**
     * 특허 ID
     * @type {number}
     * @memberof PatentResponse
     */
    id?: number;
    /**
     * 특허명
     * @type {string}
     * @memberof PatentResponse
     */
    patentTitle?: string;
    /**
     * 특허 번호
     * @type {string}
     * @memberof PatentResponse
     */
    patentNumber?: string;
    /**
     * 출원일
     * @type {Date}
     * @memberof PatentResponse
     */
    applicationDate?: Date;
}

/**
 * Check if a given object implements the PatentResponse interface.
 */
export function instanceOfPatentResponse(value: object): value is PatentResponse {
    return true;
}

export function PatentResponseFromJSON(json: any): PatentResponse {
    return PatentResponseFromJSONTyped(json, false);
}

export function PatentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'patentTitle': json['patentTitle'] == null ? undefined : json['patentTitle'],
        'patentNumber': json['patentNumber'] == null ? undefined : json['patentNumber'],
        'applicationDate': json['applicationDate'] == null ? undefined : (new Date(json['applicationDate'])),
    };
}

export function PatentResponseToJSON(json: any): PatentResponse {
    return PatentResponseToJSONTyped(json, false);
}

export function PatentResponseToJSONTyped(value?: PatentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'patentTitle': value['patentTitle'],
        'patentNumber': value['patentNumber'],
        'applicationDate': value['applicationDate'] == null ? undefined : ((value['applicationDate']).toISOString().substring(0,10)),
    };
}

