/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 특허 저자 요청 DTO
 * @export
 * @interface PatentAuthorRequest
 */
export interface PatentAuthorRequest {
    /**
     * 사용자 ID (내부 사용자)
     * @type {number}
     * @memberof PatentAuthorRequest
     */
    userId?: number;
    /**
     * 외부 인사 ID (userId와 중 하나만 입력)
     * @type {number}
     * @memberof PatentAuthorRequest
     */
    externalProfessorId?: number;
    /**
     * 저자 역할
     * @type {string}
     * @memberof PatentAuthorRequest
     */
    role?: string;
}

/**
 * Check if a given object implements the PatentAuthorRequest interface.
 */
export function instanceOfPatentAuthorRequest(value: object): value is PatentAuthorRequest {
    return true;
}

export function PatentAuthorRequestFromJSON(json: any): PatentAuthorRequest {
    return PatentAuthorRequestFromJSONTyped(json, false);
}

export function PatentAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatentAuthorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'externalProfessorId': json['externalProfessorId'] == null ? undefined : json['externalProfessorId'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function PatentAuthorRequestToJSON(json: any): PatentAuthorRequest {
    return PatentAuthorRequestToJSONTyped(json, false);
}

export function PatentAuthorRequestToJSONTyped(value?: PatentAuthorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'externalProfessorId': value['externalProfessorId'],
        'role': value['role'],
    };
}

