/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSummary } from './UserSummary';
import {
  UserSummaryFromJSON,
  UserSummaryFromJSONTyped,
  UserSummaryToJSON,
  UserSummaryToJSONTyped,
} from './UserSummary';
import type { ProjectCategorySummary } from './ProjectCategorySummary';
import {
  ProjectCategorySummaryFromJSON,
  ProjectCategorySummaryFromJSONTyped,
  ProjectCategorySummaryToJSON,
  ProjectCategorySummaryToJSONTyped,
} from './ProjectCategorySummary';
import type { ExternalProfessorSummary } from './ExternalProfessorSummary';
import {
  ExternalProfessorSummaryFromJSON,
  ExternalProfessorSummaryFromJSONTyped,
  ExternalProfessorSummaryToJSON,
  ExternalProfessorSummaryToJSONTyped,
} from './ExternalProfessorSummary';
import type { ProjectFileSummary } from './ProjectFileSummary';
import {
  ProjectFileSummaryFromJSON,
  ProjectFileSummaryFromJSONTyped,
  ProjectFileSummaryToJSON,
  ProjectFileSummaryToJSONTyped,
} from './ProjectFileSummary';

/**
 *
 * @export
 * @interface ProjectDetail
 */
export interface ProjectDetail {
  /**
   * 연구 ID
   * @type {number}
   * @memberof ProjectDetail
   */
  projectId?: number;
  /**
   * 연구 생성자 정보
   * @type {UserSummary}
   * @memberof ProjectDetail
   */
  author?: UserSummary;
  /**
   * 연구 제목
   * @type {string}
   * @memberof ProjectDetail
   */
  title?: string;
  /**
   * 연구 설명
   * @type {string}
   * @memberof ProjectDetail
   */
  content?: string;
  /**
   * 연구 시작일
   * @type {Date}
   * @memberof ProjectDetail
   */
  startDate?: Date;
  /**
   * 연구 종료일
   * @type {Date}
   * @memberof ProjectDetail
   */
  endDate?: Date;
  /**
   * 연구 책임자 목록
   * @type {Array<UserSummary>}
   * @memberof ProjectDetail
   */
  leaders?: Array<UserSummary>;
  /**
   * 연구 참여자 목록
   * @type {Array<UserSummary>}
   * @memberof ProjectDetail
   */
  participants?: Array<UserSummary>;
  /**
   * 연구 분야
   * @type {ProjectCategorySummary}
   * @memberof ProjectDetail
   */
  category?: ProjectCategorySummary;
  /**
   * 연구 비공개 여부
   * @type {boolean}
   * @memberof ProjectDetail
   */
  isPrivate?: boolean;
  /**
   * 연구 페이지 접근 가능 여부
   * @type {boolean}
   * @memberof ProjectDetail
   */
  isAccessible?: boolean;
  /**
   * 연구 상태
   * @type {string}
   * @memberof ProjectDetail
   */
  status?: ProjectDetailStatusEnum;
  /**
   * 연구 IRB 번호
   * @type {string}
   * @memberof ProjectDetail
   */
  irbId?: string;
  /**
   * 연구 DRB 번호
   * @type {string}
   * @memberof ProjectDetail
   */
  drbId?: string;
  /**
   * PI 목록
   * @type {Array<ExternalProfessorSummary>}
   * @memberof ProjectDetail
   */
  piList?: Array<ExternalProfessorSummary>;
  /**
   * 실무 교수 목록
   * @type {Array<ExternalProfessorSummary>}
   * @memberof ProjectDetail
   */
  practicalProfessors?: Array<ExternalProfessorSummary>;
  /**
   * 첨부된 파일 정보 목록
   * @type {Array<ProjectFileSummary>}
   * @memberof ProjectDetail
   */
  files?: Array<ProjectFileSummary>;
  /**
   * 첨부된 IRB 파일 정보 목록
   * @type {Array<ProjectFileSummary>}
   * @memberof ProjectDetail
   */
  irbFiles?: Array<ProjectFileSummary>;
  /**
   * 첨부된 DRB 파일 정보 목록
   * @type {Array<ProjectFileSummary>}
   * @memberof ProjectDetail
   */
  drbFiles?: Array<ProjectFileSummary>;
  /**
   * 연구 생성 시각
   * @type {Date}
   * @memberof ProjectDetail
   */
  createdAt?: Date;
  /**
   * 연구 최종 수정 시각
   * @type {Date}
   * @memberof ProjectDetail
   */
  updatedAt?: Date;
}

/**
 * @export
 */
export const ProjectDetailStatusEnum = {
  Pending: 'PENDING',
  InProgress: 'IN_PROGRESS',
  Completed: 'COMPLETED',
  Waiting: 'WAITING',
} as const;
export type ProjectDetailStatusEnum =
  (typeof ProjectDetailStatusEnum)[keyof typeof ProjectDetailStatusEnum];

/**
 * Check if a given object implements the ProjectDetail interface.
 */
export function instanceOfProjectDetail(value: object): value is ProjectDetail {
  return true;
}

export function ProjectDetailFromJSON(json: any): ProjectDetail {
  return ProjectDetailFromJSONTyped(json, false);
}

export function ProjectDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectDetail {
  if (json == null) {
    return json;
  }
  return {
    projectId: json['projectId'] == null ? undefined : json['projectId'],
    author:
      json['author'] == null ? undefined : UserSummaryFromJSON(json['author']),
    title: json['title'] == null ? undefined : json['title'],
    content: json['content'] == null ? undefined : json['content'],
    startDate:
      json['startDate'] == null ? undefined : new Date(json['startDate']),
    endDate: json['endDate'] == null ? undefined : new Date(json['endDate']),
    leaders:
      json['leaders'] == null
        ? undefined
        : (json['leaders'] as Array<any>).map(UserSummaryFromJSON),
    participants:
      json['participants'] == null
        ? undefined
        : (json['participants'] as Array<any>).map(UserSummaryFromJSON),
    category:
      json['category'] == null
        ? undefined
        : ProjectCategorySummaryFromJSON(json['category']),
    isPrivate: json['isPrivate'] == null ? undefined : json['isPrivate'],
    isAccessible:
      json['isAccessible'] == null ? undefined : json['isAccessible'],
    status: json['status'] == null ? undefined : json['status'],
    irbId: json['irbId'] == null ? undefined : json['irbId'],
    drbId: json['drbId'] == null ? undefined : json['drbId'],
    piList:
      json['piList'] == null
        ? undefined
        : (json['piList'] as Array<any>).map(ExternalProfessorSummaryFromJSON),
    practicalProfessors:
      json['practicalProfessors'] == null
        ? undefined
        : (json['practicalProfessors'] as Array<any>).map(
            ExternalProfessorSummaryFromJSON,
          ),
    files:
      json['files'] == null
        ? undefined
        : (json['files'] as Array<any>).map(ProjectFileSummaryFromJSON),
    irbFiles:
      json['irbFiles'] == null
        ? undefined
        : (json['irbFiles'] as Array<any>).map(ProjectFileSummaryFromJSON),
    drbFiles:
      json['drbFiles'] == null
        ? undefined
        : (json['drbFiles'] as Array<any>).map(ProjectFileSummaryFromJSON),
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    updatedAt:
      json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
  };
}

export function ProjectDetailToJSON(json: any): ProjectDetail {
  return ProjectDetailToJSONTyped(json, false);
}

export function ProjectDetailToJSONTyped(
  value?: ProjectDetail | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    projectId: value['projectId'],
    author: UserSummaryToJSON(value['author']),
    title: value['title'],
    content: value['content'],
    startDate:
      value['startDate'] == null
        ? undefined
        : value['startDate'].toISOString().substring(0, 10),
    endDate:
      value['endDate'] == null
        ? undefined
        : value['endDate'].toISOString().substring(0, 10),
    leaders:
      value['leaders'] == null
        ? undefined
        : (value['leaders'] as Array<any>).map(UserSummaryToJSON),
    participants:
      value['participants'] == null
        ? undefined
        : (value['participants'] as Array<any>).map(UserSummaryToJSON),
    category: ProjectCategorySummaryToJSON(value['category']),
    isPrivate: value['isPrivate'],
    isAccessible: value['isAccessible'],
    status: value['status'],
    irbId: value['irbId'],
    drbId: value['drbId'],
    piList:
      value['piList'] == null
        ? undefined
        : (value['piList'] as Array<any>).map(ExternalProfessorSummaryToJSON),
    practicalProfessors:
      value['practicalProfessors'] == null
        ? undefined
        : (value['practicalProfessors'] as Array<any>).map(
            ExternalProfessorSummaryToJSON,
          ),
    files:
      value['files'] == null
        ? undefined
        : (value['files'] as Array<any>).map(ProjectFileSummaryToJSON),
    irbFiles:
      value['irbFiles'] == null
        ? undefined
        : (value['irbFiles'] as Array<any>).map(ProjectFileSummaryToJSON),
    drbFiles:
      value['drbFiles'] == null
        ? undefined
        : (value['drbFiles'] as Array<any>).map(ProjectFileSummaryToJSON),
    createdAt:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
    updatedAt:
      value['updatedAt'] == null ? undefined : value['updatedAt'].toISOString(),
  };
}
