/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExternalProfessorRequest } from './ExternalProfessorRequest';
import {
    ExternalProfessorRequestFromJSON,
    ExternalProfessorRequestFromJSONTyped,
    ExternalProfessorRequestToJSON,
    ExternalProfessorRequestToJSONTyped,
} from './ExternalProfessorRequest';

/**
 * 
 * @export
 * @interface ProjectRequest
 */
export interface ProjectRequest {
    /**
     * 연구 제목
     * @type {string}
     * @memberof ProjectRequest
     */
    title: string;
    /**
     * 연구 설명
     * @type {string}
     * @memberof ProjectRequest
     */
    content: string;
    /**
     * 연구 책임자의 사용자 ID 리스트
     * @type {Array<number>}
     * @memberof ProjectRequest
     */
    leaderIds: Array<number>;
    /**
     * 연구 참여자의 사용자 ID 리스트
     * @type {Array<number>}
     * @memberof ProjectRequest
     */
    participantIds?: Array<number>;
    /**
     * 연구 시작일
     * @type {Date}
     * @memberof ProjectRequest
     */
    startDate: Date;
    /**
     * 연구 종료일 (있으면)
     * @type {Date}
     * @memberof ProjectRequest
     */
    endDate?: Date;
    /**
     * PI
     * @type {Array<ExternalProfessorRequest>}
     * @memberof ProjectRequest
     */
    piList?: Array<ExternalProfessorRequest>;
    /**
     * 실무 교수
     * @type {Array<ExternalProfessorRequest>}
     * @memberof ProjectRequest
     */
    practicalProfessors?: Array<ExternalProfessorRequest>;
    /**
     * IRB 번호 (있으면)
     * @type {string}
     * @memberof ProjectRequest
     */
    irbId?: string;
    /**
     * DRB 번호 (있으면)
     * @type {string}
     * @memberof ProjectRequest
     */
    drbId?: string;
    /**
     * (새로 추가된 파일의 ID만) IRB 파일 ID 리스트
     * @type {Array<string>}
     * @memberof ProjectRequest
     */
    irbFileIds?: Array<string>;
    /**
     * (새로 추가된 파일의 ID만) DRB 파일 ID 리스트
     * @type {Array<string>}
     * @memberof ProjectRequest
     */
    drbFileIds?: Array<string>;
    /**
     * (새로 추가된 파일의 ID만) 일반 첨부파일 ID 리스트
     * @type {Array<string>}
     * @memberof ProjectRequest
     */
    fileIds?: Array<string>;
    /**
     * 대기 상태 여부
     * @type {boolean}
     * @memberof ProjectRequest
     */
    isWaiting: boolean;
    /**
     * 연구 분야 아이디
     * @type {number}
     * @memberof ProjectRequest
     */
    categoryId: number;
    /**
     * 연구 비공개 여부
     * @type {boolean}
     * @memberof ProjectRequest
     */
    isPrivate: boolean;
}

/**
 * Check if a given object implements the ProjectRequest interface.
 */
export function instanceOfProjectRequest(value: object): value is ProjectRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('leaderIds' in value) || value['leaderIds'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('isWaiting' in value) || value['isWaiting'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('isPrivate' in value) || value['isPrivate'] === undefined) return false;
    return true;
}

export function ProjectRequestFromJSON(json: any): ProjectRequest {
    return ProjectRequestFromJSONTyped(json, false);
}

export function ProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'leaderIds': json['leaderIds'],
        'participantIds': json['participantIds'] == null ? undefined : json['participantIds'],
        'startDate': (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'piList': json['piList'] == null ? undefined : ((json['piList'] as Array<any>).map(ExternalProfessorRequestFromJSON)),
        'practicalProfessors': json['practicalProfessors'] == null ? undefined : ((json['practicalProfessors'] as Array<any>).map(ExternalProfessorRequestFromJSON)),
        'irbId': json['irbId'] == null ? undefined : json['irbId'],
        'drbId': json['drbId'] == null ? undefined : json['drbId'],
        'irbFileIds': json['irbFileIds'] == null ? undefined : json['irbFileIds'],
        'drbFileIds': json['drbFileIds'] == null ? undefined : json['drbFileIds'],
        'fileIds': json['fileIds'] == null ? undefined : json['fileIds'],
        'isWaiting': json['isWaiting'],
        'categoryId': json['categoryId'],
        'isPrivate': json['isPrivate'],
    };
}

export function ProjectRequestToJSON(json: any): ProjectRequest {
    return ProjectRequestToJSONTyped(json, false);
}

export function ProjectRequestToJSONTyped(value?: ProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'leaderIds': value['leaderIds'],
        'participantIds': value['participantIds'],
        'startDate': ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'piList': value['piList'] == null ? undefined : ((value['piList'] as Array<any>).map(ExternalProfessorRequestToJSON)),
        'practicalProfessors': value['practicalProfessors'] == null ? undefined : ((value['practicalProfessors'] as Array<any>).map(ExternalProfessorRequestToJSON)),
        'irbId': value['irbId'],
        'drbId': value['drbId'],
        'irbFileIds': value['irbFileIds'],
        'drbFileIds': value['drbFileIds'],
        'fileIds': value['fileIds'],
        'isWaiting': value['isWaiting'],
        'categoryId': value['categoryId'],
        'isPrivate': value['isPrivate'],
    };
}

