/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectSummary } from './ProjectSummary';
import {
  ProjectSummaryFromJSON,
  ProjectSummaryFromJSONTyped,
  ProjectSummaryToJSON,
  ProjectSummaryToJSONTyped,
} from './ProjectSummary';

/**
 *
 * @export
 * @interface ProjectFindAllResponse
 */
export interface ProjectFindAllResponse {
  /**
   *
   * @type {Array<ProjectSummary>}
   * @memberof ProjectFindAllResponse
   */
  projects?: Array<ProjectSummary>;
  /**
   *
   * @type {number}
   * @memberof ProjectFindAllResponse
   */
  totalPage?: number;
}

/**
 * Check if a given object implements the ProjectFindAllResponse interface.
 */
export function instanceOfProjectFindAllResponse(
  value: object,
): value is ProjectFindAllResponse {
  return true;
}

export function ProjectFindAllResponseFromJSON(
  json: any,
): ProjectFindAllResponse {
  return ProjectFindAllResponseFromJSONTyped(json, false);
}

export function ProjectFindAllResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectFindAllResponse {
  if (json == null) {
    return json;
  }
  return {
    projects:
      json['projects'] == null
        ? undefined
        : (json['projects'] as Array<any>).map(ProjectSummaryFromJSON),
    totalPage: json['totalPage'] == null ? undefined : json['totalPage'],
  };
}

export function ProjectFindAllResponseToJSON(
  json: any,
): ProjectFindAllResponse {
  return ProjectFindAllResponseToJSONTyped(json, false);
}

export function ProjectFindAllResponseToJSONTyped(
  value?: ProjectFindAllResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    projects:
      value['projects'] == null
        ? undefined
        : (value['projects'] as Array<any>).map(ProjectSummaryToJSON),
    totalPage: value['totalPage'],
  };
}
