/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicationUpdateRequest
 */
export interface PublicationUpdateRequest {
    /**
     * 논문 제목
     * @type {string}
     * @memberof PublicationUpdateRequest
     */
    title: string;
    /**
     * 저자
     * @type {string}
     * @memberof PublicationUpdateRequest
     */
    authors: string;
    /**
     * 학술지명
     * @type {string}
     * @memberof PublicationUpdateRequest
     */
    journal: string;
    /**
     * 게재일
     * @type {Date}
     * @memberof PublicationUpdateRequest
     */
    publicationDate?: Date;
    /**
     * DOI
     * @type {string}
     * @memberof PublicationUpdateRequest
     */
    doi?: string;
}

/**
 * Check if a given object implements the PublicationUpdateRequest interface.
 */
export function instanceOfPublicationUpdateRequest(value: object): value is PublicationUpdateRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('authors' in value) || value['authors'] === undefined) return false;
    if (!('journal' in value) || value['journal'] === undefined) return false;
    return true;
}

export function PublicationUpdateRequestFromJSON(json: any): PublicationUpdateRequest {
    return PublicationUpdateRequestFromJSONTyped(json, false);
}

export function PublicationUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicationUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'authors': json['authors'],
        'journal': json['journal'],
        'publicationDate': json['publicationDate'] == null ? undefined : (new Date(json['publicationDate'])),
        'doi': json['doi'] == null ? undefined : json['doi'],
    };
}

export function PublicationUpdateRequestToJSON(json: any): PublicationUpdateRequest {
    return PublicationUpdateRequestToJSONTyped(json, false);
}

export function PublicationUpdateRequestToJSONTyped(value?: PublicationUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'authors': value['authors'],
        'journal': value['journal'],
        'publicationDate': value['publicationDate'] == null ? undefined : ((value['publicationDate']).toISOString().substring(0,10)),
        'doi': value['doi'],
    };
}

