/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RejectLeaveRequest
 */
export interface RejectLeaveRequest {
    /**
     * 반려 사유
     * @type {string}
     * @memberof RejectLeaveRequest
     */
    rejectReason?: string;
}

/**
 * Check if a given object implements the RejectLeaveRequest interface.
 */
export function instanceOfRejectLeaveRequest(value: object): value is RejectLeaveRequest {
    return true;
}

export function RejectLeaveRequestFromJSON(json: any): RejectLeaveRequest {
    return RejectLeaveRequestFromJSONTyped(json, false);
}

export function RejectLeaveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectLeaveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rejectReason': json['rejectReason'] == null ? undefined : json['rejectReason'],
    };
}

export function RejectLeaveRequestToJSON(json: any): RejectLeaveRequest {
    return RejectLeaveRequestToJSONTyped(json, false);
}

export function RejectLeaveRequestToJSONTyped(value?: RejectLeaveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rejectReason': value['rejectReason'],
    };
}

