/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportRequest
 */
export interface ReportRequest {
    /**
     * 
     * @type {number}
     * @memberof ReportRequest
     */
    projectId?: number;
    /**
     * 
     * @type {Date}
     * @memberof ReportRequest
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof ReportRequest
     */
    content?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReportRequest
     */
    fileIds?: Array<string>;
}

/**
 * Check if a given object implements the ReportRequest interface.
 */
export function instanceOfReportRequest(value: object): value is ReportRequest {
    return true;
}

export function ReportRequestFromJSON(json: any): ReportRequest {
    return ReportRequestFromJSONTyped(json, false);
}

export function ReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'content': json['content'] == null ? undefined : json['content'],
        'fileIds': json['fileIds'] == null ? undefined : json['fileIds'],
    };
}

export function ReportRequestToJSON(json: any): ReportRequest {
    return ReportRequestToJSONTyped(json, false);
}

export function ReportRequestToJSONTyped(value?: ReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'content': value['content'],
        'fileIds': value['fileIds'],
    };
}

