/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RSSItem } from './RSSItem';
import {
    RSSItemFromJSON,
    RSSItemFromJSONTyped,
    RSSItemToJSON,
    RSSItemToJSONTyped,
} from './RSSItem';

/**
 * 
 * @export
 * @interface RSSResponse
 */
export interface RSSResponse {
    /**
     * 
     * @type {Array<RSSItem>}
     * @memberof RSSResponse
     */
    items?: Array<RSSItem>;
    /**
     * 
     * @type {number}
     * @memberof RSSResponse
     */
    totalPage?: number;
}

/**
 * Check if a given object implements the RSSResponse interface.
 */
export function instanceOfRSSResponse(value: object): value is RSSResponse {
    return true;
}

export function RSSResponseFromJSON(json: any): RSSResponse {
    return RSSResponseFromJSONTyped(json, false);
}

export function RSSResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RSSResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(RSSItemFromJSON)),
        'totalPage': json['totalPage'] == null ? undefined : json['totalPage'],
    };
}

export function RSSResponseToJSON(json: any): RSSResponse {
    return RSSResponseToJSONTyped(json, false);
}

export function RSSResponseToJSONTyped(value?: RSSResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(RSSItemToJSON)),
        'totalPage': value['totalPage'],
    };
}

