/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSummary } from './UserSummary';
import {
  UserSummaryFromJSON,
  UserSummaryFromJSONTyped,
  UserSummaryToJSON,
  UserSummaryToJSONTyped,
} from './UserSummary';

/**
 *
 * @export
 * @interface SearchUserResponse
 */
export interface SearchUserResponse {
  /**
   * 검색된 사용자 정보
   * @type {Array<UserSummary>}
   * @memberof SearchUserResponse
   */
  users?: Array<UserSummary>;
}

/**
 * Check if a given object implements the SearchUserResponse interface.
 */
export function instanceOfSearchUserResponse(
  value: object,
): value is SearchUserResponse {
  return true;
}

export function SearchUserResponseFromJSON(json: any): SearchUserResponse {
  return SearchUserResponseFromJSONTyped(json, false);
}

export function SearchUserResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SearchUserResponse {
  if (json == null) {
    return json;
  }
  return {
    users:
      json['users'] == null
        ? undefined
        : (json['users'] as Array<any>).map(UserSummaryFromJSON),
  };
}

export function SearchUserResponseToJSON(json: any): SearchUserResponse {
  return SearchUserResponseToJSONTyped(json, false);
}

export function SearchUserResponseToJSONTyped(
  value?: SearchUserResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    users:
      value['users'] == null
        ? undefined
        : (value['users'] as Array<any>).map(UserSummaryToJSON),
  };
}
