/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchProjectItem } from './SearchProjectItem';
import {
  SearchProjectItemFromJSON,
  SearchProjectItemFromJSONTyped,
  SearchProjectItemToJSON,
  SearchProjectItemToJSONTyped,
} from './SearchProjectItem';

/**
 *
 * @export
 * @interface SearchProjectResponse
 */
export interface SearchProjectResponse {
  /**
   *
   * @type {Array<SearchProjectItem>}
   * @memberof SearchProjectResponse
   */
  projects?: Array<SearchProjectItem>;
}

/**
 * Check if a given object implements the SearchProjectResponse interface.
 */
export function instanceOfSearchProjectResponse(
  value: object,
): value is SearchProjectResponse {
  return true;
}

export function SearchProjectResponseFromJSON(
  json: any,
): SearchProjectResponse {
  return SearchProjectResponseFromJSONTyped(json, false);
}

export function SearchProjectResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SearchProjectResponse {
  if (json == null) {
    return json;
  }
  return {
    projects:
      json['projects'] == null
        ? undefined
        : (json['projects'] as Array<any>).map(SearchProjectItemFromJSON),
  };
}

export function SearchProjectResponseToJSON(json: any): SearchProjectResponse {
  return SearchProjectResponseToJSONTyped(json, false);
}

export function SearchProjectResponseToJSONTyped(
  value?: SearchProjectResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    projects:
      value['projects'] == null
        ? undefined
        : (value['projects'] as Array<any>).map(SearchProjectItemToJSON),
  };
}
