/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeminarResponse } from './SeminarResponse';
import {
    SeminarResponseFromJSON,
    SeminarResponseFromJSONTyped,
    SeminarResponseToJSON,
    SeminarResponseToJSONTyped,
} from './SeminarResponse';

/**
 * 
 * @export
 * @interface SeminarFindAllResponse
 */
export interface SeminarFindAllResponse {
    /**
     * 세미나/학회 목록
     * @type {Array<SeminarResponse>}
     * @memberof SeminarFindAllResponse
     */
    seminars?: Array<SeminarResponse>;
    /**
     * 전체 페이지 수
     * @type {number}
     * @memberof SeminarFindAllResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the SeminarFindAllResponse interface.
 */
export function instanceOfSeminarFindAllResponse(value: object): value is SeminarFindAllResponse {
    return true;
}

export function SeminarFindAllResponseFromJSON(json: any): SeminarFindAllResponse {
    return SeminarFindAllResponseFromJSONTyped(json, false);
}

export function SeminarFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeminarFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'seminars': json['seminars'] == null ? undefined : ((json['seminars'] as Array<any>).map(SeminarResponseFromJSON)),
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function SeminarFindAllResponseToJSON(json: any): SeminarFindAllResponse {
    return SeminarFindAllResponseToJSONTyped(json, false);
}

export function SeminarFindAllResponseToJSONTyped(value?: SeminarFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seminars': value['seminars'] == null ? undefined : ((value['seminars'] as Array<any>).map(SeminarResponseToJSON)),
        'totalPages': value['totalPages'],
    };
}

