/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeminarResponse
 */
export interface SeminarResponse {
    /**
     * 세미나/학회 ID
     * @type {number}
     * @memberof SeminarResponse
     */
    id?: number;
    /**
     * 라벨
     * @type {string}
     * @memberof SeminarResponse
     */
    label?: SeminarResponseLabelEnum;
    /**
     * 제목
     * @type {string}
     * @memberof SeminarResponse
     */
    title?: string;
    /**
     * 시작일
     * @type {Date}
     * @memberof SeminarResponse
     */
    startDate?: Date;
    /**
     * 종료일
     * @type {Date}
     * @memberof SeminarResponse
     */
    endDate?: Date;
    /**
     * 기타 메모
     * @type {string}
     * @memberof SeminarResponse
     */
    note?: string;
    /**
     * 등록자 ID
     * @type {number}
     * @memberof SeminarResponse
     */
    userId?: number;
    /**
     * 등록자 이름
     * @type {string}
     * @memberof SeminarResponse
     */
    userName?: string;
    /**
     * 생성일시
     * @type {Date}
     * @memberof SeminarResponse
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const SeminarResponseLabelEnum = {
    Seminar: 'SEMINAR',
    Conference: 'CONFERENCE'
} as const;
export type SeminarResponseLabelEnum = typeof SeminarResponseLabelEnum[keyof typeof SeminarResponseLabelEnum];


/**
 * Check if a given object implements the SeminarResponse interface.
 */
export function instanceOfSeminarResponse(value: object): value is SeminarResponse {
    return true;
}

export function SeminarResponseFromJSON(json: any): SeminarResponse {
    return SeminarResponseFromJSONTyped(json, false);
}

export function SeminarResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeminarResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'title': json['title'] == null ? undefined : json['title'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'note': json['note'] == null ? undefined : json['note'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function SeminarResponseToJSON(json: any): SeminarResponse {
    return SeminarResponseToJSONTyped(json, false);
}

export function SeminarResponseToJSONTyped(value?: SeminarResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'title': value['title'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'note': value['note'],
        'userId': value['userId'],
        'userName': value['userName'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

