/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskPeriodResponse } from './TaskPeriodResponse';
import {
    TaskPeriodResponseFromJSON,
    TaskPeriodResponseFromJSONTyped,
    TaskPeriodResponseToJSON,
    TaskPeriodResponseToJSONTyped,
} from './TaskPeriodResponse';
import type { FileSummary } from './FileSummary';
import {
    FileSummaryFromJSON,
    FileSummaryFromJSONTyped,
    FileSummaryToJSON,
    FileSummaryToJSONTyped,
} from './FileSummary';

/**
 * 
 * @export
 * @interface TaskBasicInfoResponse
 */
export interface TaskBasicInfoResponse {
    /**
     * 소관부처
     * @type {string}
     * @memberof TaskBasicInfoResponse
     */
    ministry?: string;
    /**
     * 전문기관
     * @type {string}
     * @memberof TaskBasicInfoResponse
     */
    specializedAgency?: string;
    /**
     * 공고번호
     * @type {string}
     * @memberof TaskBasicInfoResponse
     */
    announcementNumber?: string;
    /**
     * 공고 시작일
     * @type {Date}
     * @memberof TaskBasicInfoResponse
     */
    announcementStartDate?: Date;
    /**
     * 공고 종료일
     * @type {Date}
     * @memberof TaskBasicInfoResponse
     */
    announcementEndDate?: Date;
    /**
     * 사업담당자 이름
     * @type {string}
     * @memberof TaskBasicInfoResponse
     */
    businessContactName?: string;
    /**
     * 사업담당자 소속
     * @type {string}
     * @memberof TaskBasicInfoResponse
     */
    businessContactDepartment?: string;
    /**
     * 사업담당자 이메일
     * @type {string}
     * @memberof TaskBasicInfoResponse
     */
    businessContactEmail?: string;
    /**
     * 사업담당자 전화번호
     * @type {string}
     * @memberof TaskBasicInfoResponse
     */
    businessContactPhone?: string;
    /**
     * 공고 링크
     * @type {string}
     * @memberof TaskBasicInfoResponse
     */
    announcementLink?: string;
    /**
     * 3책5공
     * @type {boolean}
     * @memberof TaskBasicInfoResponse
     */
    threeFiveRule?: boolean;
    /**
     * 과제제안요구서(RFP) 파일
     * @type {Array<FileSummary>}
     * @memberof TaskBasicInfoResponse
     */
    rfpFiles?: Array<FileSummary>;
    /**
     * 공고서류 전체 정보 파일
     * @type {Array<FileSummary>}
     * @memberof TaskBasicInfoResponse
     */
    announcementFiles?: Array<FileSummary>;
    /**
     * 연차별 목록
     * @type {Array<TaskPeriodResponse>}
     * @memberof TaskBasicInfoResponse
     */
    periods?: Array<TaskPeriodResponse>;
}

/**
 * Check if a given object implements the TaskBasicInfoResponse interface.
 */
export function instanceOfTaskBasicInfoResponse(value: object): value is TaskBasicInfoResponse {
    return true;
}

export function TaskBasicInfoResponseFromJSON(json: any): TaskBasicInfoResponse {
    return TaskBasicInfoResponseFromJSONTyped(json, false);
}

export function TaskBasicInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskBasicInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ministry': json['ministry'] == null ? undefined : json['ministry'],
        'specializedAgency': json['specializedAgency'] == null ? undefined : json['specializedAgency'],
        'announcementNumber': json['announcementNumber'] == null ? undefined : json['announcementNumber'],
        'announcementStartDate': json['announcementStartDate'] == null ? undefined : (new Date(json['announcementStartDate'])),
        'announcementEndDate': json['announcementEndDate'] == null ? undefined : (new Date(json['announcementEndDate'])),
        'businessContactName': json['businessContactName'] == null ? undefined : json['businessContactName'],
        'businessContactDepartment': json['businessContactDepartment'] == null ? undefined : json['businessContactDepartment'],
        'businessContactEmail': json['businessContactEmail'] == null ? undefined : json['businessContactEmail'],
        'businessContactPhone': json['businessContactPhone'] == null ? undefined : json['businessContactPhone'],
        'announcementLink': json['announcementLink'] == null ? undefined : json['announcementLink'],
        'threeFiveRule': json['threeFiveRule'] == null ? undefined : json['threeFiveRule'],
        'rfpFiles': json['rfpFiles'] == null ? undefined : ((json['rfpFiles'] as Array<any>).map(FileSummaryFromJSON)),
        'announcementFiles': json['announcementFiles'] == null ? undefined : ((json['announcementFiles'] as Array<any>).map(FileSummaryFromJSON)),
        'periods': json['periods'] == null ? undefined : ((json['periods'] as Array<any>).map(TaskPeriodResponseFromJSON)),
    };
}

export function TaskBasicInfoResponseToJSON(json: any): TaskBasicInfoResponse {
    return TaskBasicInfoResponseToJSONTyped(json, false);
}

export function TaskBasicInfoResponseToJSONTyped(value?: TaskBasicInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ministry': value['ministry'],
        'specializedAgency': value['specializedAgency'],
        'announcementNumber': value['announcementNumber'],
        'announcementStartDate': value['announcementStartDate'] == null ? undefined : ((value['announcementStartDate']).toISOString().substring(0,10)),
        'announcementEndDate': value['announcementEndDate'] == null ? undefined : ((value['announcementEndDate']).toISOString().substring(0,10)),
        'businessContactName': value['businessContactName'],
        'businessContactDepartment': value['businessContactDepartment'],
        'businessContactEmail': value['businessContactEmail'],
        'businessContactPhone': value['businessContactPhone'],
        'announcementLink': value['announcementLink'],
        'threeFiveRule': value['threeFiveRule'],
        'rfpFiles': value['rfpFiles'] == null ? undefined : ((value['rfpFiles'] as Array<any>).map(FileSummaryToJSON)),
        'announcementFiles': value['announcementFiles'] == null ? undefined : ((value['announcementFiles'] as Array<any>).map(FileSummaryToJSON)),
        'periods': value['periods'] == null ? undefined : ((value['periods'] as Array<any>).map(TaskPeriodResponseToJSON)),
    };
}

