/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskPeriodRequest
 */
export interface TaskPeriodRequest {
    /**
     * 연차
     * @type {number}
     * @memberof TaskPeriodRequest
     */
    yearNumber: number;
    /**
     * 시작일
     * @type {Date}
     * @memberof TaskPeriodRequest
     */
    startDate: Date;
    /**
     * 종료일
     * @type {Date}
     * @memberof TaskPeriodRequest
     */
    endDate: Date;
}

/**
 * Check if a given object implements the TaskPeriodRequest interface.
 */
export function instanceOfTaskPeriodRequest(value: object): value is TaskPeriodRequest {
    if (!('yearNumber' in value) || value['yearNumber'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function TaskPeriodRequestFromJSON(json: any): TaskPeriodRequest {
    return TaskPeriodRequestFromJSONTyped(json, false);
}

export function TaskPeriodRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskPeriodRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'yearNumber': json['yearNumber'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
    };
}

export function TaskPeriodRequestToJSON(json: any): TaskPeriodRequest {
    return TaskPeriodRequestToJSONTyped(json, false);
}

export function TaskPeriodRequestToJSONTyped(value?: TaskPeriodRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'yearNumber': value['yearNumber'],
        'startDate': ((value['startDate']).toISOString().substring(0,10)),
        'endDate': ((value['endDate']).toISOString().substring(0,10)),
    };
}

