/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileSummary } from './FileSummary';
import {
    FileSummaryFromJSON,
    FileSummaryFromJSONTyped,
    FileSummaryToJSON,
    FileSummaryToJSONTyped,
} from './FileSummary';

/**
 * 
 * @export
 * @interface TaskAgreementResponse
 */
export interface TaskAgreementResponse {
    /**
     * 협약 체결일
     * @type {Date}
     * @memberof TaskAgreementResponse
     */
    agreementDate?: Date;
    /**
     * 협약용 최종 제안서 파일
     * @type {Array<FileSummary>}
     * @memberof TaskAgreementResponse
     */
    agreementFinalProposalFiles?: Array<FileSummary>;
    /**
     * 협약용 최종 제출서류 파일
     * @type {Array<FileSummary>}
     * @memberof TaskAgreementResponse
     */
    agreementFinalSubmissionFiles?: Array<FileSummary>;
}

/**
 * Check if a given object implements the TaskAgreementResponse interface.
 */
export function instanceOfTaskAgreementResponse(value: object): value is TaskAgreementResponse {
    return true;
}

export function TaskAgreementResponseFromJSON(json: any): TaskAgreementResponse {
    return TaskAgreementResponseFromJSONTyped(json, false);
}

export function TaskAgreementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskAgreementResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'agreementDate': json['agreementDate'] == null ? undefined : (new Date(json['agreementDate'])),
        'agreementFinalProposalFiles': json['agreementFinalProposalFiles'] == null ? undefined : ((json['agreementFinalProposalFiles'] as Array<any>).map(FileSummaryFromJSON)),
        'agreementFinalSubmissionFiles': json['agreementFinalSubmissionFiles'] == null ? undefined : ((json['agreementFinalSubmissionFiles'] as Array<any>).map(FileSummaryFromJSON)),
    };
}

export function TaskAgreementResponseToJSON(json: any): TaskAgreementResponse {
    return TaskAgreementResponseToJSONTyped(json, false);
}

export function TaskAgreementResponseToJSONTyped(value?: TaskAgreementResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agreementDate': value['agreementDate'] == null ? undefined : ((value['agreementDate']).toISOString().substring(0,10)),
        'agreementFinalProposalFiles': value['agreementFinalProposalFiles'] == null ? undefined : ((value['agreementFinalProposalFiles'] as Array<any>).map(FileSummaryToJSON)),
        'agreementFinalSubmissionFiles': value['agreementFinalSubmissionFiles'] == null ? undefined : ((value['agreementFinalSubmissionFiles'] as Array<any>).map(FileSummaryToJSON)),
    };
}

