/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskPeriodRequest } from './TaskPeriodRequest';
import {
    TaskPeriodRequestFromJSON,
    TaskPeriodRequestFromJSONTyped,
    TaskPeriodRequestToJSON,
    TaskPeriodRequestToJSONTyped,
} from './TaskPeriodRequest';

/**
 * 
 * @export
 * @interface TaskRequest
 */
export interface TaskRequest {
    /**
     * 연구과제번호
     * @type {string}
     * @memberof TaskRequest
     */
    researchTaskNumber: string;
    /**
     * 과제명
     * @type {string}
     * @memberof TaskRequest
     */
    title: string;
    /**
     * RFP번호
     * @type {string}
     * @memberof TaskRequest
     */
    rfpNumber: string;
    /**
     * RFP명
     * @type {string}
     * @memberof TaskRequest
     */
    rfpName: string;
    /**
     * 사업명
     * @type {string}
     * @memberof TaskRequest
     */
    businessName: string;
    /**
     * 발주처
     * @type {string}
     * @memberof TaskRequest
     */
    issuingAgency: string;
    /**
     * 연구과제지원
     * @type {string}
     * @memberof TaskRequest
     */
    supportType: TaskRequestSupportTypeEnum;
    /**
     * 3책5공 포함 여부
     * @type {boolean}
     * @memberof TaskRequest
     */
    threeFiveRule: boolean;
    /**
     * 총 연차
     * @type {number}
     * @memberof TaskRequest
     */
    totalYears: number;
    /**
     * 현재 연차
     * @type {number}
     * @memberof TaskRequest
     */
    currentYear: number;
    /**
     * 과제 연차별 기간 목록
     * @type {Array<TaskPeriodRequest>}
     * @memberof TaskRequest
     */
    periods?: Array<TaskPeriodRequest>;
    /**
     * 주관기관
     * @type {string}
     * @memberof TaskRequest
     */
    leadInstitution: string;
    /**
     * 담당교수
     * @type {string}
     * @memberof TaskRequest
     */
    leadProfessor: string;
    /**
     * SNUH PI
     * @type {string}
     * @memberof TaskRequest
     */
    snuhPi: string;
    /**
     * 김광수교수님 역할
     * @type {string}
     * @memberof TaskRequest
     */
    professorRole: TaskRequestProfessorRoleEnum;
    /**
     * 실무 책임자 ID
     * @type {number}
     * @memberof TaskRequest
     */
    practicalManagerId: number;
    /**
     * 참여기관
     * @type {string}
     * @memberof TaskRequest
     */
    participatingInstitutions: string;
    /**
     * 진행 상태
     * @type {string}
     * @memberof TaskRequest
     */
    status?: TaskRequestStatusEnum;
}


/**
 * @export
 */
export const TaskRequestSupportTypeEnum = {
    Total: 'TOTAL',
    FirstLead: 'FIRST_LEAD',
    SecondLead: 'SECOND_LEAD',
    ThirdLead: 'THIRD_LEAD',
    FourthLead: 'FOURTH_LEAD',
    FifthLead: 'FIFTH_LEAD'
} as const;
export type TaskRequestSupportTypeEnum = typeof TaskRequestSupportTypeEnum[keyof typeof TaskRequestSupportTypeEnum];

/**
 * @export
 */
export const TaskRequestProfessorRoleEnum = {
    CoResearcher: 'CO_RESEARCHER',
    CoPrincipalInvestigator: 'CO_PRINCIPAL_INVESTIGATOR',
    PrincipalInvestigator: 'PRINCIPAL_INVESTIGATOR',
    Consignment: 'CONSIGNMENT'
} as const;
export type TaskRequestProfessorRoleEnum = typeof TaskRequestProfessorRoleEnum[keyof typeof TaskRequestProfessorRoleEnum];

/**
 * @export
 */
export const TaskRequestStatusEnum = {
    ProposalWriting: 'PROPOSAL_WRITING',
    ProposalRejected: 'PROPOSAL_REJECTED',
    PresentationPreparing: 'PRESENTATION_PREPARING',
    PresentationRejected: 'PRESENTATION_REJECTED',
    AgreementPreparing: 'AGREEMENT_PREPARING',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED'
} as const;
export type TaskRequestStatusEnum = typeof TaskRequestStatusEnum[keyof typeof TaskRequestStatusEnum];


/**
 * Check if a given object implements the TaskRequest interface.
 */
export function instanceOfTaskRequest(value: object): value is TaskRequest {
    if (!('researchTaskNumber' in value) || value['researchTaskNumber'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('rfpNumber' in value) || value['rfpNumber'] === undefined) return false;
    if (!('rfpName' in value) || value['rfpName'] === undefined) return false;
    if (!('businessName' in value) || value['businessName'] === undefined) return false;
    if (!('issuingAgency' in value) || value['issuingAgency'] === undefined) return false;
    if (!('supportType' in value) || value['supportType'] === undefined) return false;
    if (!('threeFiveRule' in value) || value['threeFiveRule'] === undefined) return false;
    if (!('totalYears' in value) || value['totalYears'] === undefined) return false;
    if (!('currentYear' in value) || value['currentYear'] === undefined) return false;
    if (!('leadInstitution' in value) || value['leadInstitution'] === undefined) return false;
    if (!('leadProfessor' in value) || value['leadProfessor'] === undefined) return false;
    if (!('snuhPi' in value) || value['snuhPi'] === undefined) return false;
    if (!('professorRole' in value) || value['professorRole'] === undefined) return false;
    if (!('practicalManagerId' in value) || value['practicalManagerId'] === undefined) return false;
    if (!('participatingInstitutions' in value) || value['participatingInstitutions'] === undefined) return false;
    return true;
}

export function TaskRequestFromJSON(json: any): TaskRequest {
    return TaskRequestFromJSONTyped(json, false);
}

export function TaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'researchTaskNumber': json['researchTaskNumber'],
        'title': json['title'],
        'rfpNumber': json['rfpNumber'],
        'rfpName': json['rfpName'],
        'businessName': json['businessName'],
        'issuingAgency': json['issuingAgency'],
        'supportType': json['supportType'],
        'threeFiveRule': json['threeFiveRule'],
        'totalYears': json['totalYears'],
        'currentYear': json['currentYear'],
        'periods': json['periods'] == null ? undefined : ((json['periods'] as Array<any>).map(TaskPeriodRequestFromJSON)),
        'leadInstitution': json['leadInstitution'],
        'leadProfessor': json['leadProfessor'],
        'snuhPi': json['snuhPi'],
        'professorRole': json['professorRole'],
        'practicalManagerId': json['practicalManagerId'],
        'participatingInstitutions': json['participatingInstitutions'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TaskRequestToJSON(json: any): TaskRequest {
    return TaskRequestToJSONTyped(json, false);
}

export function TaskRequestToJSONTyped(value?: TaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'researchTaskNumber': value['researchTaskNumber'],
        'title': value['title'],
        'rfpNumber': value['rfpNumber'],
        'rfpName': value['rfpName'],
        'businessName': value['businessName'],
        'issuingAgency': value['issuingAgency'],
        'supportType': value['supportType'],
        'threeFiveRule': value['threeFiveRule'],
        'totalYears': value['totalYears'],
        'currentYear': value['currentYear'],
        'periods': value['periods'] == null ? undefined : ((value['periods'] as Array<any>).map(TaskPeriodRequestToJSON)),
        'leadInstitution': value['leadInstitution'],
        'leadProfessor': value['leadProfessor'],
        'snuhPi': value['snuhPi'],
        'professorRole': value['professorRole'],
        'practicalManagerId': value['practicalManagerId'],
        'participatingInstitutions': value['participatingInstitutions'],
        'status': value['status'],
    };
}

