/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskMemberSummary } from './TaskMemberSummary';
import {
    TaskMemberSummaryFromJSON,
    TaskMemberSummaryFromJSONTyped,
    TaskMemberSummaryToJSON,
    TaskMemberSummaryToJSONTyped,
} from './TaskMemberSummary';
import type { FileSummary } from './FileSummary';
import {
    FileSummaryFromJSON,
    FileSummaryFromJSONTyped,
    FileSummaryToJSON,
    FileSummaryToJSONTyped,
} from './FileSummary';

/**
 * 
 * @export
 * @interface TaskProposalResponse
 */
export interface TaskProposalResponse {
    /**
     * 제안서 제출 마감일
     * @type {Date}
     * @memberof TaskProposalResponse
     */
    proposalDeadline?: Date;
    /**
     * 제안서 작성 연구원 목록
     * @type {Array<TaskMemberSummary>}
     * @memberof TaskProposalResponse
     */
    proposalWriters?: Array<TaskMemberSummary>;
    /**
     * 발주처 담당자 이름
     * @type {string}
     * @memberof TaskProposalResponse
     */
    contractorContactName?: string;
    /**
     * 발주처 담당자 부서
     * @type {string}
     * @memberof TaskProposalResponse
     */
    contractorContactDepartment?: string;
    /**
     * 발주처 담당자 이메일
     * @type {string}
     * @memberof TaskProposalResponse
     */
    contractorContactEmail?: string;
    /**
     * 발주처 담당자 전화번호
     * @type {string}
     * @memberof TaskProposalResponse
     */
    contractorContactPhone?: string;
    /**
     * 원내 담당자 이름
     * @type {string}
     * @memberof TaskProposalResponse
     */
    internalContactName?: string;
    /**
     * 원내 담당자 부서
     * @type {string}
     * @memberof TaskProposalResponse
     */
    internalContactDepartment?: string;
    /**
     * 원내 담당자 이메일
     * @type {string}
     * @memberof TaskProposalResponse
     */
    internalContactEmail?: string;
    /**
     * 원내 담당자 전화번호
     * @type {string}
     * @memberof TaskProposalResponse
     */
    internalContactPhone?: string;
    /**
     * 최종 제안서 파일
     * @type {Array<FileSummary>}
     * @memberof TaskProposalResponse
     */
    finalProposalFiles?: Array<FileSummary>;
    /**
     * 최종 제출서류 파일
     * @type {Array<FileSummary>}
     * @memberof TaskProposalResponse
     */
    finalSubmissionFiles?: Array<FileSummary>;
    /**
     * 관련 파일 목록
     * @type {Array<FileSummary>}
     * @memberof TaskProposalResponse
     */
    relatedFiles?: Array<FileSummary>;
    /**
     * 제안서 작성 회의록 파일
     * @type {Array<FileSummary>}
     * @memberof TaskProposalResponse
     */
    meetingNotesFiles?: Array<FileSummary>;
    /**
     * 과제 구성 모식도 파일 (이미지/PDF)
     * @type {Array<FileSummary>}
     * @memberof TaskProposalResponse
     */
    structureDiagramFiles?: Array<FileSummary>;
}

/**
 * Check if a given object implements the TaskProposalResponse interface.
 */
export function instanceOfTaskProposalResponse(value: object): value is TaskProposalResponse {
    return true;
}

export function TaskProposalResponseFromJSON(json: any): TaskProposalResponse {
    return TaskProposalResponseFromJSONTyped(json, false);
}

export function TaskProposalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProposalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'proposalDeadline': json['proposalDeadline'] == null ? undefined : (new Date(json['proposalDeadline'])),
        'proposalWriters': json['proposalWriters'] == null ? undefined : ((json['proposalWriters'] as Array<any>).map(TaskMemberSummaryFromJSON)),
        'contractorContactName': json['contractorContactName'] == null ? undefined : json['contractorContactName'],
        'contractorContactDepartment': json['contractorContactDepartment'] == null ? undefined : json['contractorContactDepartment'],
        'contractorContactEmail': json['contractorContactEmail'] == null ? undefined : json['contractorContactEmail'],
        'contractorContactPhone': json['contractorContactPhone'] == null ? undefined : json['contractorContactPhone'],
        'internalContactName': json['internalContactName'] == null ? undefined : json['internalContactName'],
        'internalContactDepartment': json['internalContactDepartment'] == null ? undefined : json['internalContactDepartment'],
        'internalContactEmail': json['internalContactEmail'] == null ? undefined : json['internalContactEmail'],
        'internalContactPhone': json['internalContactPhone'] == null ? undefined : json['internalContactPhone'],
        'finalProposalFiles': json['finalProposalFiles'] == null ? undefined : ((json['finalProposalFiles'] as Array<any>).map(FileSummaryFromJSON)),
        'finalSubmissionFiles': json['finalSubmissionFiles'] == null ? undefined : ((json['finalSubmissionFiles'] as Array<any>).map(FileSummaryFromJSON)),
        'relatedFiles': json['relatedFiles'] == null ? undefined : ((json['relatedFiles'] as Array<any>).map(FileSummaryFromJSON)),
        'meetingNotesFiles': json['meetingNotesFiles'] == null ? undefined : ((json['meetingNotesFiles'] as Array<any>).map(FileSummaryFromJSON)),
        'structureDiagramFiles': json['structureDiagramFiles'] == null ? undefined : ((json['structureDiagramFiles'] as Array<any>).map(FileSummaryFromJSON)),
    };
}

export function TaskProposalResponseToJSON(json: any): TaskProposalResponse {
    return TaskProposalResponseToJSONTyped(json, false);
}

export function TaskProposalResponseToJSONTyped(value?: TaskProposalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proposalDeadline': value['proposalDeadline'] == null ? undefined : ((value['proposalDeadline']).toISOString()),
        'proposalWriters': value['proposalWriters'] == null ? undefined : ((value['proposalWriters'] as Array<any>).map(TaskMemberSummaryToJSON)),
        'contractorContactName': value['contractorContactName'],
        'contractorContactDepartment': value['contractorContactDepartment'],
        'contractorContactEmail': value['contractorContactEmail'],
        'contractorContactPhone': value['contractorContactPhone'],
        'internalContactName': value['internalContactName'],
        'internalContactDepartment': value['internalContactDepartment'],
        'internalContactEmail': value['internalContactEmail'],
        'internalContactPhone': value['internalContactPhone'],
        'finalProposalFiles': value['finalProposalFiles'] == null ? undefined : ((value['finalProposalFiles'] as Array<any>).map(FileSummaryToJSON)),
        'finalSubmissionFiles': value['finalSubmissionFiles'] == null ? undefined : ((value['finalSubmissionFiles'] as Array<any>).map(FileSummaryToJSON)),
        'relatedFiles': value['relatedFiles'] == null ? undefined : ((value['relatedFiles'] as Array<any>).map(FileSummaryToJSON)),
        'meetingNotesFiles': value['meetingNotesFiles'] == null ? undefined : ((value['meetingNotesFiles'] as Array<any>).map(FileSummaryToJSON)),
        'structureDiagramFiles': value['structureDiagramFiles'] == null ? undefined : ((value['structureDiagramFiles'] as Array<any>).map(FileSummaryToJSON)),
    };
}

