/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskPeriodSummaryResponse } from './TaskPeriodSummaryResponse';
import {
    TaskPeriodSummaryResponseFromJSON,
    TaskPeriodSummaryResponseFromJSONTyped,
    TaskPeriodSummaryResponseToJSON,
    TaskPeriodSummaryResponseToJSONTyped,
} from './TaskPeriodSummaryResponse';

/**
 * 
 * @export
 * @interface TaskSummaryResponse
 */
export interface TaskSummaryResponse {
    /**
     * 과제 ID
     * @type {number}
     * @memberof TaskSummaryResponse
     */
    id?: number;
    /**
     * 연구과제번호
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    researchTaskNumber?: string;
    /**
     * 과제명
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    title?: string;
    /**
     * RFP번호
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    rfpNumber?: string;
    /**
     * RFP명
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    rfpName?: string;
    /**
     * 진행 상태
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    status?: TaskSummaryResponseStatusEnum;
    /**
     * 사업명
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    businessName?: string;
    /**
     * 발주처
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    issuingAgency?: string;
    /**
     * 연구과제지원
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    supportType?: TaskSummaryResponseSupportTypeEnum;
    /**
     * 삼책오공
     * @type {boolean}
     * @memberof TaskSummaryResponse
     */
    threeFiveRule?: boolean;
    /**
     * 총 연차
     * @type {number}
     * @memberof TaskSummaryResponse
     */
    totalYears?: number;
    /**
     * 현재 연차
     * @type {number}
     * @memberof TaskSummaryResponse
     */
    currentYear?: number;
    /**
     * 과제 전체 시작일 (첫 연차의 시작일)
     * @type {Date}
     * @memberof TaskSummaryResponse
     */
    taskStartDate?: Date;
    /**
     * 과제 전체 종료일 (마지막 연차의 종료일)
     * @type {Date}
     * @memberof TaskSummaryResponse
     */
    taskEndDate?: Date;
    /**
     * 과제 연차별 기간 목록
     * @type {Array<TaskPeriodSummaryResponse>}
     * @memberof TaskSummaryResponse
     */
    periods?: Array<TaskPeriodSummaryResponse>;
    /**
     * 주관기관
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    leadInstitution?: string;
    /**
     * 담당교수
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    leadProfessor?: string;
    /**
     * SNUH PI
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    snuhPi?: string;
    /**
     * 김광수교수님 역할
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    professorRole?: TaskSummaryResponseProfessorRoleEnum;
    /**
     * 실무 책임자 이름
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    practicalManagerName?: string;
    /**
     * 참여기관
     * @type {string}
     * @memberof TaskSummaryResponse
     */
    participatingInstitutions?: string;
}


/**
 * @export
 */
export const TaskSummaryResponseStatusEnum = {
    ProposalWriting: 'PROPOSAL_WRITING',
    ProposalRejected: 'PROPOSAL_REJECTED',
    PresentationPreparing: 'PRESENTATION_PREPARING',
    PresentationRejected: 'PRESENTATION_REJECTED',
    AgreementPreparing: 'AGREEMENT_PREPARING',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED'
} as const;
export type TaskSummaryResponseStatusEnum = typeof TaskSummaryResponseStatusEnum[keyof typeof TaskSummaryResponseStatusEnum];

/**
 * @export
 */
export const TaskSummaryResponseSupportTypeEnum = {
    Total: 'TOTAL',
    FirstLead: 'FIRST_LEAD',
    SecondLead: 'SECOND_LEAD',
    ThirdLead: 'THIRD_LEAD',
    FourthLead: 'FOURTH_LEAD',
    FifthLead: 'FIFTH_LEAD'
} as const;
export type TaskSummaryResponseSupportTypeEnum = typeof TaskSummaryResponseSupportTypeEnum[keyof typeof TaskSummaryResponseSupportTypeEnum];

/**
 * @export
 */
export const TaskSummaryResponseProfessorRoleEnum = {
    CoResearcher: 'CO_RESEARCHER',
    CoPrincipalInvestigator: 'CO_PRINCIPAL_INVESTIGATOR',
    PrincipalInvestigator: 'PRINCIPAL_INVESTIGATOR',
    Consignment: 'CONSIGNMENT'
} as const;
export type TaskSummaryResponseProfessorRoleEnum = typeof TaskSummaryResponseProfessorRoleEnum[keyof typeof TaskSummaryResponseProfessorRoleEnum];


/**
 * Check if a given object implements the TaskSummaryResponse interface.
 */
export function instanceOfTaskSummaryResponse(value: object): value is TaskSummaryResponse {
    return true;
}

export function TaskSummaryResponseFromJSON(json: any): TaskSummaryResponse {
    return TaskSummaryResponseFromJSONTyped(json, false);
}

export function TaskSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'researchTaskNumber': json['researchTaskNumber'] == null ? undefined : json['researchTaskNumber'],
        'title': json['title'] == null ? undefined : json['title'],
        'rfpNumber': json['rfpNumber'] == null ? undefined : json['rfpNumber'],
        'rfpName': json['rfpName'] == null ? undefined : json['rfpName'],
        'status': json['status'] == null ? undefined : json['status'],
        'businessName': json['businessName'] == null ? undefined : json['businessName'],
        'issuingAgency': json['issuingAgency'] == null ? undefined : json['issuingAgency'],
        'supportType': json['supportType'] == null ? undefined : json['supportType'],
        'threeFiveRule': json['threeFiveRule'] == null ? undefined : json['threeFiveRule'],
        'totalYears': json['totalYears'] == null ? undefined : json['totalYears'],
        'currentYear': json['currentYear'] == null ? undefined : json['currentYear'],
        'taskStartDate': json['taskStartDate'] == null ? undefined : (new Date(json['taskStartDate'])),
        'taskEndDate': json['taskEndDate'] == null ? undefined : (new Date(json['taskEndDate'])),
        'periods': json['periods'] == null ? undefined : ((json['periods'] as Array<any>).map(TaskPeriodSummaryResponseFromJSON)),
        'leadInstitution': json['leadInstitution'] == null ? undefined : json['leadInstitution'],
        'leadProfessor': json['leadProfessor'] == null ? undefined : json['leadProfessor'],
        'snuhPi': json['snuhPi'] == null ? undefined : json['snuhPi'],
        'professorRole': json['professorRole'] == null ? undefined : json['professorRole'],
        'practicalManagerName': json['practicalManagerName'] == null ? undefined : json['practicalManagerName'],
        'participatingInstitutions': json['participatingInstitutions'] == null ? undefined : json['participatingInstitutions'],
    };
}

export function TaskSummaryResponseToJSON(json: any): TaskSummaryResponse {
    return TaskSummaryResponseToJSONTyped(json, false);
}

export function TaskSummaryResponseToJSONTyped(value?: TaskSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'researchTaskNumber': value['researchTaskNumber'],
        'title': value['title'],
        'rfpNumber': value['rfpNumber'],
        'rfpName': value['rfpName'],
        'status': value['status'],
        'businessName': value['businessName'],
        'issuingAgency': value['issuingAgency'],
        'supportType': value['supportType'],
        'threeFiveRule': value['threeFiveRule'],
        'totalYears': value['totalYears'],
        'currentYear': value['currentYear'],
        'taskStartDate': value['taskStartDate'] == null ? undefined : ((value['taskStartDate']).toISOString().substring(0,10)),
        'taskEndDate': value['taskEndDate'] == null ? undefined : ((value['taskEndDate']).toISOString().substring(0,10)),
        'periods': value['periods'] == null ? undefined : ((value['periods'] as Array<any>).map(TaskPeriodSummaryResponseToJSON)),
        'leadInstitution': value['leadInstitution'],
        'leadProfessor': value['leadProfessor'],
        'snuhPi': value['snuhPi'],
        'professorRole': value['professorRole'],
        'practicalManagerName': value['practicalManagerName'],
        'participatingInstitutions': value['participatingInstitutions'],
    };
}

