/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskPeriodUpdateRequest
 */
export interface TaskPeriodUpdateRequest {
    /**
     * 시작일
     * @type {Date}
     * @memberof TaskPeriodUpdateRequest
     */
    startDate?: Date;
    /**
     * 종료일
     * @type {Date}
     * @memberof TaskPeriodUpdateRequest
     */
    endDate?: Date;
    /**
     * 과제 담당자 ID
     * @type {number}
     * @memberof TaskPeriodUpdateRequest
     */
    managerId?: number;
    /**
     * 과제 참여자 ID 목록
     * @type {Array<number>}
     * @memberof TaskPeriodUpdateRequest
     */
    memberIds?: Array<number>;
}

/**
 * Check if a given object implements the TaskPeriodUpdateRequest interface.
 */
export function instanceOfTaskPeriodUpdateRequest(value: object): value is TaskPeriodUpdateRequest {
    return true;
}

export function TaskPeriodUpdateRequestFromJSON(json: any): TaskPeriodUpdateRequest {
    return TaskPeriodUpdateRequestFromJSONTyped(json, false);
}

export function TaskPeriodUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskPeriodUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'managerId': json['managerId'] == null ? undefined : json['managerId'],
        'memberIds': json['memberIds'] == null ? undefined : json['memberIds'],
    };
}

export function TaskPeriodUpdateRequestToJSON(json: any): TaskPeriodUpdateRequest {
    return TaskPeriodUpdateRequestToJSONTyped(json, false);
}

export function TaskPeriodUpdateRequestToJSONTyped(value?: TaskPeriodUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'managerId': value['managerId'],
        'memberIds': value['memberIds'],
    };
}

