/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskBasicInfoUpdateRequest
 */
export interface TaskBasicInfoUpdateRequest {
    /**
     * 소관부처
     * @type {string}
     * @memberof TaskBasicInfoUpdateRequest
     */
    ministry?: string;
    /**
     * 전문기관
     * @type {string}
     * @memberof TaskBasicInfoUpdateRequest
     */
    specializedAgency?: string;
    /**
     * 공고번호
     * @type {string}
     * @memberof TaskBasicInfoUpdateRequest
     */
    announcementNumber?: string;
    /**
     * 3책5공
     * @type {boolean}
     * @memberof TaskBasicInfoUpdateRequest
     */
    threeFiveRule?: boolean;
    /**
     * 공고 시작일
     * @type {Date}
     * @memberof TaskBasicInfoUpdateRequest
     */
    announcementStartDate?: Date;
    /**
     * 공고 종료일
     * @type {Date}
     * @memberof TaskBasicInfoUpdateRequest
     */
    announcementEndDate?: Date;
    /**
     * 사업담당자 이름
     * @type {string}
     * @memberof TaskBasicInfoUpdateRequest
     */
    businessContactName?: string;
    /**
     * 사업담당자 소속
     * @type {string}
     * @memberof TaskBasicInfoUpdateRequest
     */
    businessContactDepartment?: string;
    /**
     * 사업담당자 이메일
     * @type {string}
     * @memberof TaskBasicInfoUpdateRequest
     */
    businessContactEmail?: string;
    /**
     * 사업담당자 전화번호
     * @type {string}
     * @memberof TaskBasicInfoUpdateRequest
     */
    businessContactPhone?: string;
    /**
     * 공고 링크
     * @type {string}
     * @memberof TaskBasicInfoUpdateRequest
     */
    announcementLink?: string;
    /**
     * RFP 파일 ID 목록
     * @type {Array<string>}
     * @memberof TaskBasicInfoUpdateRequest
     */
    rfpFileIds?: Array<string>;
    /**
     * 공고서류 파일 ID 목록
     * @type {Array<string>}
     * @memberof TaskBasicInfoUpdateRequest
     */
    announcementFileIds?: Array<string>;
}

/**
 * Check if a given object implements the TaskBasicInfoUpdateRequest interface.
 */
export function instanceOfTaskBasicInfoUpdateRequest(value: object): value is TaskBasicInfoUpdateRequest {
    return true;
}

export function TaskBasicInfoUpdateRequestFromJSON(json: any): TaskBasicInfoUpdateRequest {
    return TaskBasicInfoUpdateRequestFromJSONTyped(json, false);
}

export function TaskBasicInfoUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskBasicInfoUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ministry': json['ministry'] == null ? undefined : json['ministry'],
        'specializedAgency': json['specializedAgency'] == null ? undefined : json['specializedAgency'],
        'announcementNumber': json['announcementNumber'] == null ? undefined : json['announcementNumber'],
        'threeFiveRule': json['threeFiveRule'] == null ? undefined : json['threeFiveRule'],
        'announcementStartDate': json['announcementStartDate'] == null ? undefined : (new Date(json['announcementStartDate'])),
        'announcementEndDate': json['announcementEndDate'] == null ? undefined : (new Date(json['announcementEndDate'])),
        'businessContactName': json['businessContactName'] == null ? undefined : json['businessContactName'],
        'businessContactDepartment': json['businessContactDepartment'] == null ? undefined : json['businessContactDepartment'],
        'businessContactEmail': json['businessContactEmail'] == null ? undefined : json['businessContactEmail'],
        'businessContactPhone': json['businessContactPhone'] == null ? undefined : json['businessContactPhone'],
        'announcementLink': json['announcementLink'] == null ? undefined : json['announcementLink'],
        'rfpFileIds': json['rfpFileIds'] == null ? undefined : json['rfpFileIds'],
        'announcementFileIds': json['announcementFileIds'] == null ? undefined : json['announcementFileIds'],
    };
}

export function TaskBasicInfoUpdateRequestToJSON(json: any): TaskBasicInfoUpdateRequest {
    return TaskBasicInfoUpdateRequestToJSONTyped(json, false);
}

export function TaskBasicInfoUpdateRequestToJSONTyped(value?: TaskBasicInfoUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ministry': value['ministry'],
        'specializedAgency': value['specializedAgency'],
        'announcementNumber': value['announcementNumber'],
        'threeFiveRule': value['threeFiveRule'],
        'announcementStartDate': value['announcementStartDate'] == null ? undefined : ((value['announcementStartDate']).toISOString().substring(0,10)),
        'announcementEndDate': value['announcementEndDate'] == null ? undefined : ((value['announcementEndDate']).toISOString().substring(0,10)),
        'businessContactName': value['businessContactName'],
        'businessContactDepartment': value['businessContactDepartment'],
        'businessContactEmail': value['businessContactEmail'],
        'businessContactPhone': value['businessContactPhone'],
        'announcementLink': value['announcementLink'],
        'rfpFileIds': value['rfpFileIds'],
        'announcementFileIds': value['announcementFileIds'],
    };
}

