/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimelineSummary } from './TimelineSummary';
import {
    TimelineSummaryFromJSON,
    TimelineSummaryFromJSONTyped,
    TimelineSummaryToJSON,
    TimelineSummaryToJSONTyped,
} from './TimelineSummary';

/**
 * 
 * @export
 * @interface TimelineFindAllResponse
 */
export interface TimelineFindAllResponse {
    /**
     * 
     * @type {Array<TimelineSummary>}
     * @memberof TimelineFindAllResponse
     */
    timelines?: Array<TimelineSummary>;
}

/**
 * Check if a given object implements the TimelineFindAllResponse interface.
 */
export function instanceOfTimelineFindAllResponse(value: object): value is TimelineFindAllResponse {
    return true;
}

export function TimelineFindAllResponseFromJSON(json: any): TimelineFindAllResponse {
    return TimelineFindAllResponseFromJSONTyped(json, false);
}

export function TimelineFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimelineFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timelines': json['timelines'] == null ? undefined : ((json['timelines'] as Array<any>).map(TimelineSummaryFromJSON)),
    };
}

export function TimelineFindAllResponseToJSON(json: any): TimelineFindAllResponse {
    return TimelineFindAllResponseToJSONTyped(json, false);
}

export function TimelineFindAllResponseToJSONTyped(value?: TimelineFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timelines': value['timelines'] == null ? undefined : ((value['timelines'] as Array<any>).map(TimelineSummaryToJSON)),
    };
}

