/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateJournalRequest
 */
export interface UpdateJournalRequest {
    /**
     * 저널명
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    journalName: string;
    /**
     * 저널 분류
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    category: UpdateJournalRequestCategoryEnum;
    /**
     * 출판사
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    publisher: string;
    /**
     * 출판 국가
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    publishCountry: string;
    /**
     * ISBN
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    isbn?: string;
    /**
     * ISSN
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    issn: string;
    /**
     * eISSN
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    eissn?: string;
    /**
     * JIF (Journal Impact Factor)
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    jif: string;
    /**
     * JCR Rank
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    jcrRank: string;
    /**
     * Issue
     * @type {string}
     * @memberof UpdateJournalRequest
     */
    issue?: string;
}


/**
 * @export
 */
export const UpdateJournalRequestCategoryEnum = {
    Sci: 'SCI',
    Scie: 'SCIE',
    Scopus: 'SCOPUS',
    Esci: 'ESCI'
} as const;
export type UpdateJournalRequestCategoryEnum = typeof UpdateJournalRequestCategoryEnum[keyof typeof UpdateJournalRequestCategoryEnum];


/**
 * Check if a given object implements the UpdateJournalRequest interface.
 */
export function instanceOfUpdateJournalRequest(value: object): value is UpdateJournalRequest {
    if (!('journalName' in value) || value['journalName'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('publisher' in value) || value['publisher'] === undefined) return false;
    if (!('publishCountry' in value) || value['publishCountry'] === undefined) return false;
    if (!('issn' in value) || value['issn'] === undefined) return false;
    if (!('jif' in value) || value['jif'] === undefined) return false;
    if (!('jcrRank' in value) || value['jcrRank'] === undefined) return false;
    return true;
}

export function UpdateJournalRequestFromJSON(json: any): UpdateJournalRequest {
    return UpdateJournalRequestFromJSONTyped(json, false);
}

export function UpdateJournalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateJournalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'journalName': json['journalName'],
        'category': json['category'],
        'publisher': json['publisher'],
        'publishCountry': json['publishCountry'],
        'isbn': json['isbn'] == null ? undefined : json['isbn'],
        'issn': json['issn'],
        'eissn': json['eissn'] == null ? undefined : json['eissn'],
        'jif': json['jif'],
        'jcrRank': json['jcrRank'],
        'issue': json['issue'] == null ? undefined : json['issue'],
    };
}

export function UpdateJournalRequestToJSON(json: any): UpdateJournalRequest {
    return UpdateJournalRequestToJSONTyped(json, false);
}

export function UpdateJournalRequestToJSONTyped(value?: UpdateJournalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'journalName': value['journalName'],
        'category': value['category'],
        'publisher': value['publisher'],
        'publishCountry': value['publishCountry'],
        'isbn': value['isbn'],
        'issn': value['issn'],
        'eissn': value['eissn'],
        'jif': value['jif'],
        'jcrRank': value['jcrRank'],
        'issue': value['issue'],
    };
}

