/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserStatusRequest
 */
export interface UpdateUserStatusRequest {
    /**
     * 사용자 상태
     * @type {string}
     * @memberof UpdateUserStatusRequest
     */
    status: UpdateUserStatusRequestStatusEnum;
}


/**
 * @export
 */
export const UpdateUserStatusRequestStatusEnum = {
    Active: 'ACTIVE',
    OnLeave: 'ON_LEAVE',
    Resigned: 'RESIGNED'
} as const;
export type UpdateUserStatusRequestStatusEnum = typeof UpdateUserStatusRequestStatusEnum[keyof typeof UpdateUserStatusRequestStatusEnum];


/**
 * Check if a given object implements the UpdateUserStatusRequest interface.
 */
export function instanceOfUpdateUserStatusRequest(value: object): value is UpdateUserStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdateUserStatusRequestFromJSON(json: any): UpdateUserStatusRequest {
    return UpdateUserStatusRequestFromJSONTyped(json, false);
}

export function UpdateUserStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function UpdateUserStatusRequestToJSON(json: any): UpdateUserStatusRequest {
    return UpdateUserStatusRequestToJSONTyped(json, false);
}

export function UpdateUserStatusRequestToJSONTyped(value?: UpdateUserStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

