/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserPasswordRequest
 */
export interface UpdateUserPasswordRequest {
    /**
     * 현재 비밀번호
     * @type {string}
     * @memberof UpdateUserPasswordRequest
     */
    currentPassword?: string;
    /**
     * 새 비밀번호
     * @type {string}
     * @memberof UpdateUserPasswordRequest
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the UpdateUserPasswordRequest interface.
 */
export function instanceOfUpdateUserPasswordRequest(value: object): value is UpdateUserPasswordRequest {
    return true;
}

export function UpdateUserPasswordRequestFromJSON(json: any): UpdateUserPasswordRequest {
    return UpdateUserPasswordRequestFromJSONTyped(json, false);
}

export function UpdateUserPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'] == null ? undefined : json['currentPassword'],
        'newPassword': json['newPassword'] == null ? undefined : json['newPassword'],
    };
}

export function UpdateUserPasswordRequestToJSON(json: any): UpdateUserPasswordRequest {
    return UpdateUserPasswordRequestToJSONTyped(json, false);
}

export function UpdateUserPasswordRequestToJSONTyped(value?: UpdateUserPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
    };
}

