/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAuthorRequest
 */
export interface UpdateAuthorRequest {
    /**
     * 저자 목록
     * @type {string}
     * @memberof UpdateAuthorRequest
     */
    authors?: string;
    /**
     * 구분(기고, 저서 중 택1)
     * @type {string}
     * @memberof UpdateAuthorRequest
     */
    authorType?: UpdateAuthorRequestAuthorTypeEnum;
    /**
     * 출판일
     * @type {Date}
     * @memberof UpdateAuthorRequest
     */
    publicationDate?: Date;
    /**
     * 발행처
     * @type {string}
     * @memberof UpdateAuthorRequest
     */
    publicationHouse?: string;
    /**
     * 출판사
     * @type {string}
     * @memberof UpdateAuthorRequest
     */
    publisher?: string;
    /**
     * 출판물명
     * @type {string}
     * @memberof UpdateAuthorRequest
     */
    publicationName?: string;
    /**
     * 제목
     * @type {string}
     * @memberof UpdateAuthorRequest
     */
    title?: string;
    /**
     * ISBN
     * @type {string}
     * @memberof UpdateAuthorRequest
     */
    isbn?: string;
}


/**
 * @export
 */
export const UpdateAuthorRequestAuthorTypeEnum = {
    Contribution: 'CONTRIBUTION',
    Book: 'BOOK'
} as const;
export type UpdateAuthorRequestAuthorTypeEnum = typeof UpdateAuthorRequestAuthorTypeEnum[keyof typeof UpdateAuthorRequestAuthorTypeEnum];


/**
 * Check if a given object implements the UpdateAuthorRequest interface.
 */
export function instanceOfUpdateAuthorRequest(value: object): value is UpdateAuthorRequest {
    return true;
}

export function UpdateAuthorRequestFromJSON(json: any): UpdateAuthorRequest {
    return UpdateAuthorRequestFromJSONTyped(json, false);
}

export function UpdateAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAuthorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'authors': json['authors'] == null ? undefined : json['authors'],
        'authorType': json['authorType'] == null ? undefined : json['authorType'],
        'publicationDate': json['publicationDate'] == null ? undefined : (new Date(json['publicationDate'])),
        'publicationHouse': json['publicationHouse'] == null ? undefined : json['publicationHouse'],
        'publisher': json['publisher'] == null ? undefined : json['publisher'],
        'publicationName': json['publicationName'] == null ? undefined : json['publicationName'],
        'title': json['title'] == null ? undefined : json['title'],
        'isbn': json['isbn'] == null ? undefined : json['isbn'],
    };
}

export function UpdateAuthorRequestToJSON(json: any): UpdateAuthorRequest {
    return UpdateAuthorRequestToJSONTyped(json, false);
}

export function UpdateAuthorRequestToJSONTyped(value?: UpdateAuthorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authors': value['authors'],
        'authorType': value['authorType'],
        'publicationDate': value['publicationDate'] == null ? undefined : ((value['publicationDate']).toISOString().substring(0,10)),
        'publicationHouse': value['publicationHouse'],
        'publisher': value['publisher'],
        'publicationName': value['publicationName'],
        'title': value['title'],
        'isbn': value['isbn'],
    };
}

