/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFileRequest
 */
export interface UploadFileRequest {
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequest
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequest
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequest
     */
    extension?: string;
    /**
     * 
     * @type {number}
     * @memberof UploadFileRequest
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof UploadFileRequest
     */
    domainType?: UploadFileRequestDomainTypeEnum;
}


/**
 * @export
 */
export const UploadFileRequestDomainTypeEnum = {
    Project: 'PROJECT',
    Timeline: 'TIMELINE',
    Report: 'REPORT'
} as const;
export type UploadFileRequestDomainTypeEnum = typeof UploadFileRequestDomainTypeEnum[keyof typeof UploadFileRequestDomainTypeEnum];


/**
 * Check if a given object implements the UploadFileRequest interface.
 */
export function instanceOfUploadFileRequest(value: object): value is UploadFileRequest {
    return true;
}

export function UploadFileRequestFromJSON(json: any): UploadFileRequest {
    return UploadFileRequestFromJSONTyped(json, false);
}

export function UploadFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'extension': json['extension'] == null ? undefined : json['extension'],
        'size': json['size'] == null ? undefined : json['size'],
        'domainType': json['domainType'] == null ? undefined : json['domainType'],
    };
}

export function UploadFileRequestToJSON(json: any): UploadFileRequest {
    return UploadFileRequestToJSONTyped(json, false);
}

export function UploadFileRequestToJSONTyped(value?: UploadFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'fileName': value['fileName'],
        'extension': value['extension'],
        'size': value['size'],
        'domainType': value['domainType'],
    };
}

