/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectCategorySummary } from './ProjectCategorySummary';
import {
    ProjectCategorySummaryFromJSON,
    ProjectCategorySummaryFromJSONTyped,
    ProjectCategorySummaryToJSON,
    ProjectCategorySummaryToJSONTyped,
} from './ProjectCategorySummary';

/**
 * 
 * @export
 * @interface UserItem
 */
export interface UserItem {
    /**
     * 사용자 ID
     * @type {number}
     * @memberof UserItem
     */
    userId?: number;
    /**
     * 이메일 주소
     * @type {string}
     * @memberof UserItem
     */
    email?: string;
    /**
     * 이름
     * @type {string}
     * @memberof UserItem
     */
    name?: string;
    /**
     * 기관
     * @type {string}
     * @memberof UserItem
     */
    organization?: string;
    /**
     * 부서
     * @type {string}
     * @memberof UserItem
     */
    department?: string;
    /**
     * 소속 (있으면)
     * @type {string}
     * @memberof UserItem
     */
    affiliation?: UserItemAffiliationEnum;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UserItem
     */
    profileImageUrl?: string;
    /**
     * 연구 분야 목록
     * @type {Array<ProjectCategorySummary>}
     * @memberof UserItem
     */
    categories?: Array<ProjectCategorySummary>;
    /**
     * 좌석 번호
     * @type {string}
     * @memberof UserItem
     */
    seatNumber?: string;
    /**
     * 전화번호
     * @type {string}
     * @memberof UserItem
     */
    phoneNumber?: string;
    /**
     * 학력
     * @type {string}
     * @memberof UserItem
     */
    education?: string;
}


/**
 * @export
 */
export const UserItemAffiliationEnum = {
    Professor: 'PROFESSOR',
    CoPrincipalInvestigator: 'CO_PRINCIPAL_INVESTIGATOR',
    PostdoctoralResearcher: 'POSTDOCTORAL_RESEARCHER',
    PhdStudent: 'PHD_STUDENT',
    MastersStudent: 'MASTERS_STUDENT',
    TranslationalMedicineTrainee: 'TRANSLATIONAL_MEDICINE_TRAINEE',
    ResearcherOrIntern: 'RESEARCHER_OR_INTERN',
    AdministrativeStaff: 'ADMINISTRATIVE_STAFF'
} as const;
export type UserItemAffiliationEnum = typeof UserItemAffiliationEnum[keyof typeof UserItemAffiliationEnum];


/**
 * Check if a given object implements the UserItem interface.
 */
export function instanceOfUserItem(value: object): value is UserItem {
    return true;
}

export function UserItemFromJSON(json: any): UserItem {
    return UserItemFromJSONTyped(json, false);
}

export function UserItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserItem {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'department': json['department'] == null ? undefined : json['department'],
        'affiliation': json['affiliation'] == null ? undefined : json['affiliation'],
        'profileImageUrl': json['profileImageUrl'] == null ? undefined : json['profileImageUrl'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(ProjectCategorySummaryFromJSON)),
        'seatNumber': json['seatNumber'] == null ? undefined : json['seatNumber'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'education': json['education'] == null ? undefined : json['education'],
    };
}

export function UserItemToJSON(json: any): UserItem {
    return UserItemToJSONTyped(json, false);
}

export function UserItemToJSONTyped(value?: UserItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'email': value['email'],
        'name': value['name'],
        'organization': value['organization'],
        'department': value['department'],
        'affiliation': value['affiliation'],
        'profileImageUrl': value['profileImageUrl'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(ProjectCategorySummaryToJSON)),
        'seatNumber': value['seatNumber'],
        'phoneNumber': value['phoneNumber'],
        'education': value['education'],
    };
}

