/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAccountEmailRequest
 */
export interface UserAccountEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof UserAccountEmailRequest
     */
    : string;
}

/**
 * Check if a given object implements the UserAccountEmailRequest interface.
 */
export function instanceOfUserAccountEmailRequest(value: object): value is UserAccountEmailRequest {
    if (!('' in value) || value[''] === undefined) return false;
    return true;
}

export function UserAccountEmailRequestFromJSON(json: any): UserAccountEmailRequest {
    return UserAccountEmailRequestFromJSONTyped(json, false);
}

export function UserAccountEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccountEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '': json['비밀번호'],
    };
}

export function UserAccountEmailRequestToJSON(json: any): UserAccountEmailRequest {
    return UserAccountEmailRequestToJSONTyped(json, false);
}

export function UserAccountEmailRequestToJSONTyped(value?: UserAccountEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '비밀번호': value[''],
    };
}

