/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 시작 연월
 * @export
 * @interface UserEducationRequestStartYearMonth
 */
export interface UserEducationRequestStartYearMonth {
    /**
     * 
     * @type {number}
     * @memberof UserEducationRequestStartYearMonth
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof UserEducationRequestStartYearMonth
     */
    month?: UserEducationRequestStartYearMonthMonthEnum;
    /**
     * 
     * @type {number}
     * @memberof UserEducationRequestStartYearMonth
     */
    monthValue?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserEducationRequestStartYearMonth
     */
    leapYear?: boolean;
}


/**
 * @export
 */
export const UserEducationRequestStartYearMonthMonthEnum = {
    January: 'JANUARY',
    February: 'FEBRUARY',
    March: 'MARCH',
    April: 'APRIL',
    May: 'MAY',
    June: 'JUNE',
    July: 'JULY',
    August: 'AUGUST',
    September: 'SEPTEMBER',
    October: 'OCTOBER',
    November: 'NOVEMBER',
    December: 'DECEMBER'
} as const;
export type UserEducationRequestStartYearMonthMonthEnum = typeof UserEducationRequestStartYearMonthMonthEnum[keyof typeof UserEducationRequestStartYearMonthMonthEnum];


/**
 * Check if a given object implements the UserEducationRequestStartYearMonth interface.
 */
export function instanceOfUserEducationRequestStartYearMonth(value: object): value is UserEducationRequestStartYearMonth {
    return true;
}

export function UserEducationRequestStartYearMonthFromJSON(json: any): UserEducationRequestStartYearMonth {
    return UserEducationRequestStartYearMonthFromJSONTyped(json, false);
}

export function UserEducationRequestStartYearMonthFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserEducationRequestStartYearMonth {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'monthValue': json['monthValue'] == null ? undefined : json['monthValue'],
        'leapYear': json['leapYear'] == null ? undefined : json['leapYear'],
    };
}

export function UserEducationRequestStartYearMonthToJSON(json: any): UserEducationRequestStartYearMonth {
    return UserEducationRequestStartYearMonthToJSONTyped(json, false);
}

export function UserEducationRequestStartYearMonthToJSONTyped(value?: UserEducationRequestStartYearMonth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'month': value['month'],
        'monthValue': value['monthValue'],
        'leapYear': value['leapYear'],
    };
}

