/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSubAffiliationRequest
 */
export interface UserSubAffiliationRequest {
    /**
     * 기관
     * @type {string}
     * @memberof UserSubAffiliationRequest
     */
    organization: string;
    /**
     * 부서
     * @type {string}
     * @memberof UserSubAffiliationRequest
     */
    department?: string;
    /**
     * 구분
     * @type {string}
     * @memberof UserSubAffiliationRequest
     */
    position?: string;
}

/**
 * Check if a given object implements the UserSubAffiliationRequest interface.
 */
export function instanceOfUserSubAffiliationRequest(value: object): value is UserSubAffiliationRequest {
    if (!('organization' in value) || value['organization'] === undefined) return false;
    return true;
}

export function UserSubAffiliationRequestFromJSON(json: any): UserSubAffiliationRequest {
    return UserSubAffiliationRequestFromJSONTyped(json, false);
}

export function UserSubAffiliationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSubAffiliationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': json['organization'],
        'department': json['department'] == null ? undefined : json['department'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function UserSubAffiliationRequestToJSON(json: any): UserSubAffiliationRequest {
    return UserSubAffiliationRequestToJSONTyped(json, false);
}

export function UserSubAffiliationRequestToJSONTyped(value?: UserSubAffiliationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': value['organization'],
        'department': value['department'],
        'position': value['position'],
    };
}

