/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProjectItem } from './UserProjectItem';
import {
  UserProjectItemFromJSON,
  UserProjectItemFromJSONTyped,
  UserProjectItemToJSON,
  UserProjectItemToJSONTyped,
} from './UserProjectItem';

/**
 *
 * @export
 * @interface UserProjectFindAllResponse
 */
export interface UserProjectFindAllResponse {
  /**
   *
   * @type {Array<UserProjectItem>}
   * @memberof UserProjectFindAllResponse
   */
  projects?: Array<UserProjectItem>;
}

/**
 * Check if a given object implements the UserProjectFindAllResponse interface.
 */
export function instanceOfUserProjectFindAllResponse(
  value: object,
): value is UserProjectFindAllResponse {
  return true;
}

export function UserProjectFindAllResponseFromJSON(
  json: any,
): UserProjectFindAllResponse {
  return UserProjectFindAllResponseFromJSONTyped(json, false);
}

export function UserProjectFindAllResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserProjectFindAllResponse {
  if (json == null) {
    return json;
  }
  return {
    projects:
      json['projects'] == null
        ? undefined
        : (json['projects'] as Array<any>).map(UserProjectItemFromJSON),
  };
}

export function UserProjectFindAllResponseToJSON(
  json: any,
): UserProjectFindAllResponse {
  return UserProjectFindAllResponseToJSONTyped(json, false);
}

export function UserProjectFindAllResponseToJSONTyped(
  value?: UserProjectFindAllResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    projects:
      value['projects'] == null
        ? undefined
        : (value['projects'] as Array<any>).map(UserProjectItemToJSON),
  };
}
