/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeaveDetail } from './LeaveDetail';
import {
    LeaveDetailFromJSON,
    LeaveDetailFromJSONTyped,
    LeaveDetailToJSON,
    LeaveDetailToJSONTyped,
} from './LeaveDetail';

/**
 * 
 * @export
 * @interface UserLeaveResponse
 */
export interface UserLeaveResponse {
    /**
     * 총 연차 수
     * @type {number}
     * @memberof UserLeaveResponse
     */
    annualLeaveCount?: number;
    /**
     * 사용한 연차 수
     * @type {number}
     * @memberof UserLeaveResponse
     */
    usedLeaveCount?: number;
    /**
     * 
     * @type {Array<LeaveDetail>}
     * @memberof UserLeaveResponse
     */
    leaves?: Array<LeaveDetail>;
    /**
     * 
     * @type {number}
     * @memberof UserLeaveResponse
     */
    totalPage?: number;
}

/**
 * Check if a given object implements the UserLeaveResponse interface.
 */
export function instanceOfUserLeaveResponse(value: object): value is UserLeaveResponse {
    return true;
}

export function UserLeaveResponseFromJSON(json: any): UserLeaveResponse {
    return UserLeaveResponseFromJSONTyped(json, false);
}

export function UserLeaveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLeaveResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'annualLeaveCount': json['annualLeaveCount'] == null ? undefined : json['annualLeaveCount'],
        'usedLeaveCount': json['usedLeaveCount'] == null ? undefined : json['usedLeaveCount'],
        'leaves': json['leaves'] == null ? undefined : ((json['leaves'] as Array<any>).map(LeaveDetailFromJSON)),
        'totalPage': json['totalPage'] == null ? undefined : json['totalPage'],
    };
}

export function UserLeaveResponseToJSON(json: any): UserLeaveResponse {
    return UserLeaveResponseToJSONTyped(json, false);
}

export function UserLeaveResponseToJSONTyped(value?: UserLeaveResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'annualLeaveCount': value['annualLeaveCount'],
        'usedLeaveCount': value['usedLeaveCount'],
        'leaves': value['leaves'] == null ? undefined : ((value['leaves'] as Array<any>).map(LeaveDetailToJSON)),
        'totalPage': value['totalPage'],
    };
}

