/* tslint:disable */
/* eslint-disable */
/**
 * BMI-LAB Web API
 * BMI-LAB을 관리하기 위한 웹 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProjectCategoryFindAllResponse } from '../models/index';
import {
  ProjectCategoryFindAllResponseFromJSON,
  ProjectCategoryFindAllResponseToJSON,
} from '../models/index';

/**
 *
 */
export class ProjectCategoryControllerApi extends runtime.BaseAPI {
  /**
   */
  async getAllProjectCategoriesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProjectCategoryFindAllResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('JWT', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/project-categories`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProjectCategoryFindAllResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async getAllProjectCategories(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProjectCategoryFindAllResponse> {
    const response = await this.getAllProjectCategoriesRaw(initOverrides);
    return await response.value();
  }
}
